### ISSUE TITLE
Sanctum of Domination Support

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DBM-Retail#513]
**Sanctum of Domination**
- The Tarragrue
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- The Eye of the Jailer
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- The Nine
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Remnant of Ner'zhul
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Soulrender Dormazain
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Painsmith Raznal
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Guardian of the First Ones
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Fatescribe Roh-Kalo
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Kel'Thuzad
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Sylvanas Windrunner
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties

**Comment by MysticalOS** [comment]
**Tazavesh, the Veiled Market**
- Zo'phex the Sentinel
  - [ ] Mod created with loading, stats, and combat detection
  - [ ] Mod drycoded with warnings/timers/feature
  - [ ] Encounter tested with mod and drycode bugs squashed, post testing
  - [ ] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [ ] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [ ] Mod finished with real data from remaining difficulties
- The Bazaar
  - [ ] Mod created with loading, stats, and combat detection
  - [ ] Mod drycoded with warnings/timers/feature
  - [ ] Encounter tested with mod and drycode bugs squashed, post testing
  - [ ] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [ ] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [ ] Mod finished with real data from remaining difficulties
- Mailroom Mayhem
  - [ ] Mod created with loading, stats, and combat detection
  - [ ] Mod drycoded with warnings/timers/feature
  - [ ] Encounter tested with mod and drycode bugs squashed, post testing
  - [ ] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [ ] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [ ] Mod finished with real data from remaining difficulties
- Au'myza's Oasis
  - [ ] Mod created with loading, stats, and combat detection
  - [ ] Mod drycoded with warnings/timers/feature
  - [ ] Encounter tested with mod and drycode bugs squashed, post testing
  - [ ] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [ ] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [ ] Mod finished with real data from remaining difficulties
- So'azmi
  - [ ] Mod created with loading, stats, and combat detection
  - [ ] Mod drycoded with warnings/timers/feature
  - [ ] Encounter tested with mod and drycode bugs squashed, post testing
  - [ ] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [ ] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [ ] Mod finished with real data from remaining difficulties
- Hylbrande
  - [ ] Mod created with loading, stats, and combat detection
  - [ ] Mod drycoded with warnings/timers/feature
  - [ ] Encounter tested with mod and drycode bugs squashed, post testing
  - [ ] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [ ] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [ ] Mod finished with real data from remaining difficulties
- Timecap'n Hooktail
  - [ ] Mod created with loading, stats, and combat detection
  - [ ] Mod drycoded with warnings/timers/feature
  - [ ] Encounter tested with mod and drycode bugs squashed, post testing
  - [ ] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [ ] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [ ] Mod finished with real data from remaining difficulties
- So'leah
  - [ ] Mod created with loading, stats, and combat detection
  - [ ] Mod drycoded with warnings/timers/feature
  - [ ] Encounter tested with mod and drycode bugs squashed, post testing
  - [ ] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [ ] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [ ] Mod finished with real data from remaining difficulties

**Comment by MysticalOS** [comment]
**Shadowlands**
- Mor'geth, Tormentor of the Damned
  - [x] Mod created with loading, stats, and combat detection
  - [ ] Live timer data inputted into mod
  - [ ] Encounter mod tested with mod and drycode bugs squashed, post testing

**Comment by MysticalOS** [comment]
- [ ] For Sylvanas phase 1: yell how many Barbed Arrow stacks you have if you have more than 3 whenever Domination Chains are being cast (to help coordinate chain soaks on larger raid sizes)

**Comment by SzRental** [comment]
Request from Discord -
Takkero — Today at 3:50 PM
in the EYE OF THE JAILER can we have a say timer 5/4/3/2/1 on MISERY (black pool)

**Comment by MysticalOS** [comment]
Considering this closed, anything now is just requests and reported issues, but the raid has been considered fully supported since LFR sylvanas shipped
