### ISSUE TITLE
Classic ERA, Lua error

### ISSUE THREAD

**Issue by Slivo-fr** [DeadlyBossMods/DBM-Retail#676]
**Describe the bug**
Lua error

**Do you have an error log of what happened?**
Upaded today, happened 6 times since then, while rushing the stokade with a warrior, I can't exacly say what triggers it

6x DBM-Core\DBM-Core-ce984a9.lua:5995: attempt to call global 'GetNumTrackedAchievements' (a nil value)
DBM-Core\DBM-Core-ce984a9.lua:5995: in function `StartCombat'
DBM-Core\DBM-Core-ce984a9.lua:6185: in function `handler'
DBM-Core\DBM-Core-ce984a9.lua:910: in function <DBM-Core\DBM-Core.lua:897>
DBM-Core\DBM-Core-ce984a9.lua:931: in function <DBM-Core\DBM-Core.lua:929>

Locals:
InCombatSkipped

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
1.13.79

**Was it working in a previous version? If yes, which was the last good one?**
Yes, it was working before the last update, can't say exacly which version I had

**Comment by QartemisT** [comment]
Update to the latest alpha version :)
