### ISSUE TITLE
Can DBM not mark the Mistcaller's Illusionary Clone?

### ISSUE THREAD

**Issue by gotex007** [DeadlyBossMods/DBM-Retail#684]
I'd much like if DBM could stop marking the Mistcaller's Illusionary Clone. It makes it really annoying to skull mark the correct one and the markers on the clones have never been a useful feature the entire expansion. Sure I can disable it on my end but everybody has DBM so it doesn't even matter that I do.

**Comment by MysticalOS** [comment]
i disagree on it not being useful, I've seen many M+ groups not even mark a skull, just go "it's circle" or "it's star" from the pre existing marks. None the less, I'm still going to make it off by default to match littewigs behavior of not havin feature at all. Hopefully those that actually liked it can figure out how to turn it back on if they choose.
