### ISSUE TITLE
Sepulcher of the First Ones Support

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DBM-Retail#691]
- Vigilant Guardian
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Dausegne, the Fallen Oracle
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Artificer Xy'mox
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Prototype Pantheon
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Lihuvim, Principal Architect
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Skolex, the Insatiable Ravener
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Halondrus the Reclaimer
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Anduin Wrynn
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Lords of Dread
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Rygelon
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Zovaal
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [ ] Mod finished with real data from remaining difficulties

**Comment by MysticalOS** [comment]
Mods that received insufficient data on ptr to complete

Anduin: Heroic P2.5+, Mythic P1.5+
Hal: Mythic P2+
xymox: Mythic P3
Pantheon: Mythic P3

**Comment by MysticalOS** [comment]
Unchecked everything on hal, consider that mod untested on any difficulty at this point. Blizzard kicked most of fight to curb and made a new one. mods back to being a full drycode effectively.

**Comment by MysticalOS** [comment]
Marking Rygelon as drycoded but with caveat that it's only going to really be half effective with probably near useless AI timers since it's very very unclear how the bosses phasing works. You think one thing from journal summary but then read spell data and it disagrees with journal summary and it just leaves it very unclear which you should trust.

**Comment by MysticalOS** [comment]
ALl mythic testing now considered obsolete and all mods deflagged as mythic complete until vetted on mythic live

**Comment by Siodar** [comment]
Good morning. last night was attempting to do this raid. when i got a LUA error. as i went through my addons to figure out which one was causing it. it ended up being the Sepulcher DBM and one other addon. i did turn off both and no more LUA.  i returned on this addon only and got the LUA again. just wanted to let you know what happened. if need more info. i can post what i can find. thank you for the excellent addons you all make.

**Comment by MysticalOS** [comment]
Without the error, we can't do anything to correct it sadly.. You'll have to provide more details such as exact error or at very least say which boss and line number it said it was on

**Comment by Siodar** [comment]
![image](https://user-images.githubusercontent.com/102478096/160302353-b93b2436-36f6-45fc-8f83-22ba313dd1ef.png)

**Comment by MysticalOS** [comment]
That's actually nothing to do with DBM at all.

**Comment by Siodar** [comment]
ok, well like i said, the LUA stop popping when i turned off the Seplucher part of DBM off. was just letting you all know.

**Comment by dysreflexia** [comment]
was getting an error during the jailer encounter last night. Installed version  9.2.10

Video  https://youtu.be/eGoV8ysvloA   seem to always  happen at this part of the fight
![Discord_QL2MFlD7il](https://user-images.githubusercontent.com/102785059/161205797-9a109321-c559-4005-b865-4cde4c96dd94.png)

**Comment by MysticalOS** [comment]
@dysreflexia that was fixed in https://github.com/DeadlyBossMods/DBM-Retail/commit/c00da207c478c20139defa46ed9c51a26f6d731f earlier today. It's mostly an ignorable error, as it'd only happen once per pull when boss casts a specific spellId version of one of his spells. no timers or warnings should actually be missing. If the error popup itself is annoying you can use the alpha version, or install bugsack/buggrabber to have less intrusive error reporting that doesn't pop up mid fight.

**Comment by Siodar** [comment]
getting this today..  
![image](https://user-images.githubusercontent.com/102478096/161360821-9400726f-feac-4a0d-a380-909ceb4a3ce2.png)

**Comment by MysticalOS** [comment]
@Siodar  I just want to mention that this issue is for tracking the sepulcher of first ones development progress, new issues should go in new tickets. That particular issue is because you are using a discontinued weak aura that's not properly using callbacks and is accessing a global varaible that no longer exists. This is because that weak aura is no longer maintained. Delete that one and use https://wago.io/RaidAbilityTimeline instead
