### ISSUE TITLE
Every reload in every raid 20-40 lua errors. Only DBM active.

### ISSUE THREAD

**Issue by rouoko** [DeadlyBossMods/DBM-Retail#729]
5x DBM-EmeraldNightmare\Renferal.lua:74: attempt to concatenate field 'HEROIC_ICON' (a nil value)
[string "@DBM-EmeraldNightmare\Renferal.lua"]:74: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@DBM-Core\DBM-Core-74470f8.lua"]:3416: in function `LoadMod'
[string "@DBM-Core\DBM-Core-74470f8.lua"]:3359: in function `LoadModsOnDemand'
[string "@DBM-Core\DBM-Core-74470f8.lua"]:3297: in function `func'
[string "@DBM-Core\modules\Scheduler.lua"]:171: in function <DBM-Core\modules\Scheduler.lua:162>

Locals:
mod = <table> {
 timers = <table> {
 }
 categorySort = <table> {
 }
 instanceId = 768
 modelId = 69474
 SyncThreshold = 8
 numBoss = 1
 modId = "DBM-EmeraldNightmare"
 inCombatOnlyEvents = <table> {
 }
 combatInfo = <table> {
 }
 zones = <table> {
 }
 revision = 20210905144823
 Options = <table> {
 }
 DefaultOptions = <table> {
 }
 iconRestore = <table> {
 }
 hotfixNoticeRev = 15357
 usedIcons = <table> {
 }
 addon = <table> {
 }
 creatureId = 106087
 encounterId = 1876
 id = "1744"
 specwarns = <table> {
 }
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 optionCategories = <table> {
 }
}
L = <table> {
 name = "Elerethe Renferal"
}
warnSpiderForm = <table> {
 type = "spell"
 spellId = 210326
 option = "announce210326spell"
 color = <table> {
 }
 text = "Arachnid Form"
 announceType = "spell"
 combinedcount = 0
 mod = <table> {
 }
 combinedtext = <table> {
 }
 sound = 1
 icon = 1370997
 spellName = "Arachnid Form"
}
warnFeedingTime = <table> {
 type = "spell"
 spellId = 212364
 option = "announce212364spell"
 color = <table> {
 }
 text = "Feeding Time"
 announceType = "spell"
 combinedcount = 0
 mod = <table> {
 }
 combinedtext = <table> {
 }
 sound = 1
 icon = 132196
 spellName = "Feeding Time"
}
warnWebWrap = <table> {
 type = "target"
 spellId = 212514
 option = "announceother212514target"
 color = <table> {
 }
 text = "Web Wrapped on >%s<"
 announceType = "target"
 combinedcount = 0
 mod = <table> {
 }
 combinedtext = <table> {
 }
 sound = 1
 icon = 132196
 spellName = "Web Wrapped"
}
warnNecroticVenom = <table> {
 type = "target"
 spellId = 218831
 option = "announceother218831target"
 color = <table> {
 }
 text = "Necrotic Venom on >%s<"
 announceType = "target"
 combinedcount = 0
 mod = <table> {
 }
 combinedtext = <table> {
 }
 sound = 1
 icon = 132107
 spellName = "Necrotic Venom"
}
warnWebOfPain = <table> {
 combinedcount = 0
 mod = <table> {
 }
 option = "warnWebOfPain"
 icon = 237431
 combinedtext = <table> {
 }
 text = ">%s< is linked to >%s<"
 sound = 1
 color = <table> {
 }
}
warnNightmareSpawn = <table> {
 type = "spell"
 spellId = 218630
 option = "announce218630spell"
 color = <table> {
 }
 text = "Nightmare Spawn"
 announceType = "spell"
 combinedcount = 0
 mod = <table> {
 }
 combinedtext = <table> {
 }
 sound = 1
 icon = 1357796
 spellName = "Nightmare Spawn"
}
warnRocForm = <table> {
 type = "spell"
 spellId = 210308
 option = "announce210308spell"
 color = <table> {
 }
 text = "Darkwing Form"
 announceType = "spell"
 combinedcount = 0
 mod = <table> {
 }
 combinedtext = <table> {
 }
 sound = 1
 icon = 852827
 spellName = "Darkwing Form"
}
warnTwistingShadows = <table> {
 type = "targetcount"
 spellId = 210864
 option = "announceother210864targetcount"
 color = <table> {
 }
 text = "Twisting Shadows (%s) on >%s<"
 announceType = "targetcount"
 combinedcount = 0
 mod = <table> {
 }
 combinedtext = <table> {
 }
 sound = 1
 icon = 1022950
 spellName = "Twisting Shadows"
}
warnViolentWinds = <table> {
 type = "target"
 spellId = 218124
 option = "announceother218124target"
 color = <table> {
 }
 text = "Violent Winds on >%s<"
 announceType = "target"
 combinedcount = 0
 mod = <table> {
 }
 combinedtext = <table> {
 }
 sound = 1
 icon = 1029595
 spellName = "Violent Winds"
}
specWarnFeedingTime = <table> {
 voiceOptionId = "Voice212364"
 hasVoice = 2
 spellId = 212364
 icon = 132196
 option = "SpecWarn212364switch"
 text = "Feeding Time - switch targets"
 flash = 1
 combinedcount = 0
 mod = <table> {
 }
 announceType = "switch"
 type = "switch"
 combinedtext = <table> {
 }
 sound = true
 spellName = "Feeding Time"
}
specWarnVenomousPool = <table> {
 voiceOptionId = "Voice213124"
 hasVoice = 2
 spellId = 213124
 icon = 236271
 option = "SpecWarn213124move"
 text = "Venomous Pool - move away"
 flash = 1
 combinedcount = 0
 mod = <table> {
 }
 announceType = "move"
 type = "move"
 combinedtext = <table> {
 }
 sound = true
 spellName = "Venomous Pool"
}
specWarnWebWrap = <table> {
 voiceOptionId = "Voice212512"
 hasVoice = 6
 spellId = 212512
 icon = 237430
 option = "SpecWarn21251

**Comment by QartemisT** [comment]
Hi there,

It appears that either your DBM-Core or DBM-Legion are outdated, the latest versions of both are;
DBM-Legion: r29
DBM-Core: 9.1.27
