### ISSUE TITLE
DBM-Sepulcher\Lihuvim.lua:251: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by linaori** [DeadlyBossMods/DBM-Retail#741]
**Describe the bug**
Not necessarily a bug, but I get this Lua error. I figured I'd report it just in case as I found it through Bugsack/Bug grabber. I did quickly 

**Do you have an error log of what happened?**
```
24x DBM-Sepulcher\Lihuvim.lua:251: attempt to index field '?' (a nil value)
[string "@DBM-Sepulcher\Lihuvim.lua"]:251: in function `handler'
[string "@DBM-Core\DBM-Core-fc80d94.lua"]:884: in function <DBM-Core\DBM-Core.lua:871>
[string "=(tail call)"]: ?
[string "@DBM-Core\DBM-Core-fc80d94.lua"]:884: in function <DBM-Core\DBM-Core.lua:871>

Locals:
Skipped (In Encounter)
```

**To Reproduce**
During the fight this happens every time the boss pulls the orbs, I forgot what the spell name is.

**Screenshots**
-

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
no, I didn't get a chance to test this without ElvUI

**Which version of DeadlyBossMods are you using?**
9.2.1 (2022/03/02 11:49:57)

**Was it working in a previous version? If yes, which was the last good one?**
-

**Additional context**
-

**Comment by MysticalOS** [comment]
That's fixed in alpha, a new update will go out soon to address it. Thanks for reporting though, not many do that so quickly :)
