### ISSUE TITLE
Error type message in chat

### ISSUE THREAD

**Issue by Siodar** [DeadlyBossMods/DBM-Retail#748]
**Describe the bug**
 This message just pops up randomly but often in chat. also seems to only happen when in raids or 5 man groups.

**Do you have an error log of what happened?**
 
![image](https://user-images.githubusercontent.com/102478096/162066039-453aa4b8-d0f2-4176-ac76-20f744097c51.png)

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?** yes

**Which version of DeadlyBossMods are you using?** latest version from Curseforge.

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
IT's because of a bad weak aura, remove the phoguild raid ability timeline and use the updated timeline weak aura instead available here https://wago.io/RaidAbilityTimeline if you still want to use the timeline
