### ISSUE TITLE
[Prototype Pantheon] timer for hand of destruction (same phase) not refreshing after first cast

### ISSUE THREAD

**Issue by REVERSE-MISAYA** [DeadlyBossMods/DBM-Retail#754]
**Describe the bug**
The timer for hand of destruction (for the current phase) is not showing again after the first cast of hand of hand of destruction.  
After the phase ends, DBM sends a new update to the timer, which is too late, because hand of destruction can be casted twice in the same phase.
I tested this on heroic difficulty, but I am pretty sure it is the same for all difficulties.

**Do you have an error log of what happened?**
I dont have a log, but this could be related to dbm using two different spellids for hand of destruction (361789 and 361791)

[https://github.com/DeadlyBossMods/DBM-Retail/blob/master/DBM-Sepulcher/PrototypePantheon.lua#L109](url)
[https://github.com/DeadlyBossMods/DBM-Retail/blob/master/DBM-Sepulcher/PrototypePantheon.lua#L882](url)

**To Reproduce**
1. start the boss encounter, the first timer for hand of destruction shows up.
2. after the first cast of hand of destruction, the timer never shows up again until the phase ends

**Screenshots**
none available

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I use default UI.

**Which version of DeadlyBossMods are you using?**
DBM-9.2.13

**Was it working in a previous version? If yes, which was the last good one?**
I dont know, I only started to notice it just recently.

**Additional context**
I double checked if the timers actually got refreshed with the callbacks provided by DBM:

```
DBM:RegisterCallback("DBM_TimerStart", Update)
DBM:RegisterCallback("DBM_TimerUpdate", Update)
DBM:RegisterCallback("DBM_TimerStop", Update)
```

like I said before, an update is only send after the phase ends, but not during the phase.

**Comment by MysticalOS** [comment]
that'd be a strange change on blizzards end, if they removed that spellId from detection. the one I'm using is 1 second faster than SPELL_CAST_START and it's an Id not in combat log, just unit event. so I assume then none of warnings go off for it at all during entire fight?

**Comment by REVERSE-MISAYA** [comment]
yes, the callbacks were only updating for spellId: 361789

**Comment by MysticalOS** [comment]
Redundancy was added to latest alpha to make sure this doesn't happen anymore. Thanks for report
