### ISSUE TITLE
Heroic Skolex

### ISSUE THREAD

**Issue by zalidthebur** [DeadlyBossMods/DBM-Retail#755]
**Describe the bug**

Tank and Retch timings are out.
Both tanks have said the tank timings are out. I've also noticed that the retch timings are out on 3 and 5 iirc. Could be out on 7 too, not sure.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, though I do not use Elvui.

**Which version of DeadlyBossMods are you using?**
9.2.14 on Thurs 21 April.

**Was it working in a previous version? If yes, which was the last good one?**
No idea as we've only just started progression on heroic.

**Additional context**
Happy to install a recorder for next week if that helps and you can point me to one.
One of our raidiers did say that her BigWigs was okay.

**Comment by MysticalOS** [comment]
What does out mean? too slow too fast?

This boss has serious spell queuing problems so the timers will never be precise, give more details and I'll know what to look for though,

**Comment by MysticalOS** [comment]
I reviewed boss a bit and found no problems with any of timers except tank combo, which now seems to be too short after each burrow and that seems to be because they finally fixed a bug where the boss sometimes continued gaining energy while burrowed, which caused him to tank combo without shortening immediately when he came out. with that fixed, it seems save to extend timer now for burrows which may improve accuracy. I pushed this updated code to mod in the new release i'm putting out in a few minutes to fix another jailer bug. I'll leave issue open for tracking but will be curious how it feels on 9.2.16

**Comment by zalidthebur** [comment]
Thanks for the replies and changes to the tanking. It could be that issue that was causing the retch timing to be out as well.
iirc the retch timer would be up, then a tank combo would happen, then the retch. Going by memory here, so not 100% sure ;-)
I'll see how it goes next week and let you know.

**Comment by MysticalOS** [comment]
if two things come off cd at same time he'll aways favor tank combo first. Knowing this will just let you know retch will be pushed off til after tank combo.

**Comment by zalidthebur** [comment]
Agreed. It's probably a queuing issue like you mentioned. So many bosses are like that now that timers are just a best guess :-D

**Comment by zalidthebur** [comment]
It's just that this was consistently happening, so felt more like a addon timing issue. We'll see :-)

**Comment by MysticalOS** [comment]
well I did tweak behavior of tank timer to make that timer adjust when boss burrows so that should feel better. I could technically also just detect that if tank combo starts, extend retch timer, but that won't really tell you whether or not he'll do retch or tank combo when they are so close. it would just visually tell you the obvious so that wouldn't be much of an addition.

**Comment by MysticalOS** [comment]
Was there an update to how the mod feels now?

**Comment by zalidthebur** [comment]
Sorry to not get back to you sooner.
1st week tanks said things looked good, but 2nd week they said timers were out. The retch issue is still there. But I can see that it is being stopped by the tank mechanic.
I did try to record last week, but as it was the 1st time I'd tried it, I was not aware of the 2 hour time limit. I plan to turn it on just for the fight tomorrow, so I can look at it while not doing the fight.

**Comment by MysticalOS** [comment]
I'd want more details what they mean for second week.

**Comment by zalidthebur** [comment]
Totally understand. But the feedback I had was minimal. So I plan to make sure there is more info this week.

**Comment by zalidthebur** [comment]
Hi,

I've reviewed my video of the fight from last night and these are my findings.

Tank combo 3 is out. Coming up when Skolex at only 69 energy.
Retch 3 is out. Coming up while he is doing Tank combo 3.

Tank combo 5 is out. Coming up when Skolex at only 72 energy.
Retch 5 is out. Coming up while he is doing Tank combo 5.

Tank combo 7 is out. Coming up when Skolex at only 72 energy.
Retch 7 is out. Coming up while he is doing Tank combo 7.

Link to video: https://drive.google.com/file/d/1dX36uYm9Ht1qqfkfQCv9sZJp_A9ZKM7s/view?usp=sharing

Link to Warcraft Logs: https://www.warcraftlogs.com/reports/AQw19Gj8FWTCqyR2#fight=24

Hope this helps :-)

**Comment by MysticalOS** [comment]
I mean ordering doesn't matter. that's going to be inconsistent based on when you force burrows.

Same with timings, they won'ta lways be at same time stamp. What matters is whether or nto the tank combo timer updating on burrow is working correctly.

**Comment by MysticalOS** [comment]
Ie is the timer ever late now (combo coming out when timer still says 3 seconds or something)

**Comment by zalidthebur** [comment]
The timers are not late. They are both always early.
Tank combo and Retch after burrow is always out by about 12 seconds.
We are using the standard strategy of forcing burrow on every other Retch.
I've uploaded the video to YouTube as well: https://www.youtube.com/watch?v=QrgvOjg_2D8

**Comment by zalidthebur** [comment]
Burrow 1: 1.13min
Tank Combo 3: 1.21min
Retch 3: 1.38min

Burrow 2: 2.25min
Tank Combo 5: 2.38min
Retch 5: 2.53min

Burrow 3: 3.42min
Tank Combo 5: 3.55min
Retch 5: 4.10min

**Comment by zalidthebur** [comment]
The above are your timers and where they appear in the video. Hopefully that helps.

**Comment by MysticalOS** [comment]
Appreciate the info, but declining this issue as it's just not worth effort for such an easy straight forward boss who has obvious spell queueing problems. Only so much time and effort I can give and I must allocate it forward to dragonflight now.
