### ISSUE TITLE
Github deposits for all content plz

### ISSUE THREAD

**Issue by Gundor** [DeadlyBossMods/DBM-Retail#763]
Please put on github deposits all your works, not only "retail" content.

Thank's for all users who don't want to use overwolf/curseforge

**Comment by QartemisT** [comment]
ALL of the projects are available through github, wago, curseforge.
I'm not sure to which part you're confused doesn't exist, however if you mention specifics, I can find links for you. Otherwise, you can find them all under the DeadlyBossMods project.

**Comment by MysticalOS** [comment]
In fact, all the main ones are pinned (TBC, Vanilla, PVP, etc)
