### ISSUE TITLE
Hakkar the Soulflayer Error

### ISSUE THREAD

**Issue by jimakaturbo** [DeadlyBossMods/DBM-Retail#765]
When doing keystone De Other Side +15, on the boss fight Hakkar the Soulflayer would spam an error message to chat.
Error message is 
[19:57:06] <DBM> Error while executing callback function: 0000013F31BB3710 for event DBM_TimerUpdate: Interface\AddOns\WeakAuras\GenericTrigger.lua:2860: attempt to compare number with nil
[19:57:06] <DBM> Error while executing callback function: 0000013F31BB3710 for event DBM_TimerUpdate: Interface\AddOns\WeakAuras\GenericTrigger.lua:2860: attempt to compare number with nil

I didn't try turning off every addon. I don't have ElvUI

Error when using DBM version 9.2.19 (2022/05/31 14:47:21) 

I didn't get this error using DBM version 9.2.18
I will try turning off addons Prat and Weakauras to see if that helps.

**Comment by MysticalOS** [comment]
this error indicates it's a weak aura that needs updating that's causing issue. Likely something that's not updated for triggers properly. To diagnose problem though would need to actually know what week aura is triggering event. I'll also tag someone on WA to look at this

**Comment by mrbuds** [comment]
Line 2860 of GenericTrigger.lua for last release of WeakAuras does not handle DBM_TimerUpdate callback, i think the Weakauras used is outdated

https://github.com/WeakAuras/WeakAuras2/blob/4.0.2/WeakAuras/GenericTrigger.lua#L2860

**Comment by jimakaturbo** [comment]
Sorry about that. I updated Weakauras and Error stopped happening.
