### ISSUE TITLE
Some dungeon trash announcements no longer work since 9.2.5.

### ISSUE THREAD

**Issue by gotex007** [DeadlyBossMods/DBM-Retail#766]
Several important announcements from DBM straight up don't happen anymore in 9.2.5 like Withering Discharge, Deadly Thrust, and Invigorating Fish Stick. It's really been throwing me off and I've been waiting to see if you guys already knew about it and would fix it without me submitting an issue report but it hasn't happened. I've verified they're ticked in the options and are supposed to be going off and others I know have the same problem so I can only help this gets resolved very soon.

**Comment by MysticalOS** [comment]
they worked before 9.2.5?
is DBM up to date and functioning on other bosses/warnings? if it's no up to date 9.2.5 would have hard disabled DBM until it's updated.

**Comment by gotex007** [comment]
They worked prior to 9.2.5, yes. Most things still work as expected but there are a number of important trash announcements that do not and I've only been running keys. I'm on version 9.2.19, provided by CurseForge.

**Comment by gotex007** [comment]
I can't solo mythic An Affront of Challengers due to Opportunity Strikes but I know Withering Discharge is one of the offending spells.

Invigorating Fish Stick does not announce if I'm not targeting the Murkbrine Scalebinder.

Deadly Thrust no longer announces unless you're in tank spec.

[WoWCombatLog-061322_114458 - Copy.txt](https://github.com/DeadlyBossMods/DBM-Retail/files/8892755/WoWCombatLog-061322_114458.-.Copy.txt)

I don't have an extensive list of the offending spells off the top of my head but I definitely remember these three so those are the ones I attempted to test.

**Comment by MysticalOS** [comment]
Deadly thrust is only on by default for tanks, you can enable it for anyone.

Almost all interrupt spells require the caster to be your target and your interrupt spell to be off CD to show announcement by default. That's how the interrupt filter works. If you don't like that behavior you just change the way the filter works in this panel https://github.com/DeadlyBossMods/DBM-Retail/wiki/%5BGuide%5D-DBM-Global-Filter-Options (no picture of filter but it's on same screen further down)

both fish stick and withering discharge go through interrupt filter check

**Comment by gotex007** [comment]
Did you guys change that? That's not how either for those types of spells were working before. Deadly Thrust was definitely notifying me as a non-tank and incredibly important casts like Invigorating Fish Stick and Withering Discharge were definitely warning when not targeted and if my interrupt is on CD. Invigorating Fish Stick isn't even an interruptible spell; it has to be CCed. Withering Discharge can also be CCed to stop it as it does not recast.

**Comment by MysticalOS** [comment]
That hasn't been changed since launch that I can think of. Certainly not changed for 9.2.5.

anyways just change your interrupt filter setting to a different one worded to what you want..I can change deadly thrust to be on by default for everyone though.

**Comment by gotex007** [comment]
So I've went and dug through some random old streams and as far as interrupt functionality and Deadly Thrust I guess you must be right. I'm not sure how I remember it being different but I'll try playing around with the interrupt settings. I see that Deadly Thrust unticks itself when you change to a non-tank spec so it would be nice if there was some option to have it always be on at least.

However, when it comes to Invigorating Fish Stick I am right. It is hard to find decent clips of it but I found 3 from prior to 9.2.5.
[Clip #1 (LOUD WARNING, German)](https://www.youtube.com/watch?v=nj8kUTPMIws&t=27s), [Clip #2 (Chinese)](https://youtu.be/NUMWZCUFea0?t=302), and [Clip #3 (American)](https://youtu.be/x_bByhPPyNI?t=102). In these clips they are most definitely not targeting a Murkbrine Scalebinder when it casts but the announcement goes through which is not how it currently functions since at the moment the announcement does not happen unless you are targeting the casting Murkbrine Scalebinder.

**Comment by MysticalOS** [comment]
any setting change should stick, for that spec/char. but obviously if you change spec, or character it'll be on default setting until THAT character changes it

**Comment by gotex007** [comment]
> as for those clips, maybe they changed the interrupt filter setting?

Are you sure? Because Invigorating Fish Stick is not an interrupt.

**Comment by MysticalOS** [comment]
I edited comment as you were replying after double checking that one

**Comment by MysticalOS** [comment]
I think the problem here is the combat check that had to be added does in fact require SOMEONE in group to be targetting mob, doesn't have to be you, can be anyone else in group but any mob not actively being targeted by a group member can't be checked for UnitAffectingCombat and thus warning is filtered

**Comment by gotex007** [comment]
Yeah I'm definitely in combat when I'm the only person in there and it's casting it. Is there a way to change it to actually reflect the mob's combat state instead? Or make an exception just for the Murkbrine Scalebinder or even just the Invigorating Fish Stick ability?

Out of curiosity do you have any examples on hand for what required that change? I didn't run Tazavesh before it became a Mythic+ dungeon.

**Comment by MysticalOS** [comment]
It is using the mobs combat state, it's just not possible to know it without a valid Unit ID, such as target, focus, party1-party5 target, etc

I can maybe add nameplate scanning in there too but that would add a lot of overhead.

**Comment by gotex007** [comment]
Yeah I just can't think of anything off the top of my head that mobs cast outside of combat that DBM would announce (outside of maybe Torghast or open world) so I was hoping you had some specific dungeon examples of spells on hand. I appreciate you taking the time to talk all this out with me though.

**Comment by gotex007** [comment]
Having the option to toggle on/off Deadly Thrust account-wide would be nice so I don't have to try it toggling on and off every spec of every character.

> Maybe I can add a new checkbox to disable the "is affecting combat" filter fo rusers who'd rather have false warnings, than missing good ones.

Maybe this too. Still curious about what the specific cases were and maybe be able to toggle it per dungeon if Gambit isn't one of the reported cases.

**Comment by MysticalOS** [comment]
I just redid code to make it better. The latest alpha should now be able to identify units affecting combat via more methods (such as nameplates).

**Comment by gotex007** [comment]
Okay. I appreciate the effort. Hopefully I will no longer miss Fish Sticks and get Deadly Thrusted.
