### ISSUE TITLE
Sire Denathrius Fight

### ISSUE THREAD

**Issue by Peanut366** [DeadlyBossMods/DBM-Retail#796]
**Describe the bug**
While doing Sire Denathrius on LFR with Fated affex, three LUA errors populated.

**Do you have an error log of what happened?**
Message: ...nterface\AddOns\DBM-CastleNathria\SireDenathrius.lua:787: attempt to index field '?' (a nil value)
Time: Wed Aug  3 13:09:53 2022
Count: 4
Stack: ...nterface\AddOns\DBM-CastleNathria\SireDenathrius.lua:787: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\DBM-CastleNathria\SireDenathrius.lua"]:787: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:926: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:913>

Locals: 

Message: ...nterface\AddOns\DBM-CastleNathria\SireDenathrius.lua:660: attempt to index field '?' (a nil value)
Time: Wed Aug  3 13:09:23 2022
Count: 2
Stack: ...nterface\AddOns\DBM-CastleNathria\SireDenathrius.lua:660: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\DBM-CastleNathria\SireDenathrius.lua"]:660: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:926: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:913>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:926: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:913>

Locals: 

Message: ...nterface\AddOns\DBM-CastleNathria\SireDenathrius.lua:423: attempt to index field '?' (a nil value)
Time: Wed Aug  3 13:09:42 2022
Count: 4
Stack: ...nterface\AddOns\DBM-CastleNathria\SireDenathrius.lua:423: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\DBM-CastleNathria\SireDenathrius.lua"]:423: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:926: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:913>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:926: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:913>

Locals: 

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
I need more information, exactly what boss phase you were in when they came up, whether or not other warnings/timers worked correctly.

I can see the line number of error but not the actual cause (was phase nil? was spellid?)

**Comment by MysticalOS** [comment]
Any update on this? any further errors?

**Comment by Peanut366** [comment]
Omg I am so sorry I meant to get back to you. No, it seems to be resolved. Whatever the problem was it was just with the fated affix from the first time Sire was effected with it. This new dispel affix is working as intended with your mod.
