### ISSUE TITLE
LUA ERROR - On entering Torghast

### ISSUE THREAD

**Issue by Wyr3d** [DeadlyBossMods/DBM-Retail#799]
**Describe the bug**

Nothing, I was just entering the portal

**Do you have an error log of what happened?**

Message: Interface\AddOns\DBM-Core\DBM-Core.lua:3270: attempt to index field '?' (a nil value)
Time: Thu Aug  4 14:01:38 2022
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:3270: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:3270: in function `CheckAvailableMods'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:3397: in function `func'
[string "@Interface\AddOns\DBM-Core\modules\Scheduler.lua"]:171: in function <Interface\AddOns\DBM-Core\modules\Scheduler.lua:162>

**Comment by MysticalOS** [comment]
This should be fixed in latest release, grab it it and retest

**Comment by Wyr3d** [comment]
Pretty sure I updated my addons yesterday, but I will take another look

**Comment by MysticalOS** [comment]
It was updated 3x yesterday. first two updates had this bug, 3rd SHOULD fix it.
