### ISSUE TITLE
DBM not working for any Shadowlands M+ Dungeons

### ISSUE THREAD

**Issue by darenjacobs** [DeadlyBossMods/DBM-Retail#801]
Not only are the bars not showing up the way the did prior to the seaons 4 patch, but there is no sound associated with events in the dungeons.

**Comment by Molkree** [comment]
https://twitter.com/deadlybossmods/status/1554985582060871680

**Comment by darenjacobs** [comment]
Thank you I realize this change (removal of dungeons from core) was the root of my issue.
