### ISSUE TITLE
[gfcbaaab] WoW compleatly freeze in Huntsman Altimor fight.

### ISSUE THREAD

**Issue by Tga123** [DeadlyBossMods/DBM-Retail#802]
**Describe the bug**
9.2.31-4-gfcbaaab Alpha build from curseforge compleatly freeze WoW in Huntsman Altimor Fated fight.
9.2.31 Release build dont do that.

**Do you have an error log of what happened?**
Nope, game freeze. Only Alt+F4.

**To Reproduce**
Start fighting with Huntsman Altimor in Fated Castle Nathria.
Just pull and evade not produce freeze.

**Screenshots**
Nope.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No. But i not use serios ui mods like ElvUI.

**Which version of DeadlyBossMods are you using?**
9.2.31-4-gfcbaaab

**Was it working in a previous version? If yes, which was the last good one?**
Works fine with 9.2.31 Release.

**Additional context**
Nope.

**Comment by MysticalOS** [comment]
Should be fixed in latest commit
https://github.com/DeadlyBossMods/DBM-Retail/commit/bc12bd99a1f4f6d2537b5eb67248018324b22244
