### ISSUE TITLE
Auto logging missing CHALLENGE_MODE_START for M+

### ISSUE THREAD

**Issue by psiklos** [DeadlyBossMods/DBM-Retail#803]
Warcraftlogs was unable to determine the instance for my M+ runs with the combatlogs created with the most recent (9.2.32) version of dbm.
I compared some previous logs and it seems that the buggy logs are missing something called CHALLENGE_MODE_START at the beginning.

Combat log with 9.2.31
`9/4 09:12:33.737  COMBAT_LOG_VERSION,19,ADVANCED_LOG_ENABLED,1,BUILD_VERSION,9.2.7,PROJECT_ID,1
9/4 09:12:33.737  ZONE_CHANGE,2441,"Tazavesh, the Veiled Market",8
9/4 09:12:33.737  MAP_CHANGE,1989,"Tazavesh, the Veiled Market",4050.000000,3155.000000,-627.750000,-1970.250000
9/4 09:12:33.737  CHALLENGE_MODE_END,2441,0,0,0,0.000000,0.000000
9/4 09:12:33.737  SPELL_AURA_REMOVED,Player-1403-09D72FAA,"Zerox-Draenor",0x512,0x0,Player-1403-09D72FAA,"Zerox-Draenor",0x512,0x0,57724,"Sated",0x1,DEBUFF
9/4 09:12:34.162  CHALLENGE_MODE_START,"Tazavesh, the Veiled Market",2441,391,17,[9,6,3,131]`

Combat log with 9.2.32
`9/3 23:36:58.403  COMBAT_LOG_VERSION,19,ADVANCED_LOG_ENABLED,1,BUILD_VERSION,9.2.7,PROJECT_ID,1
9/3 23:36:58.403  ZONE_CHANGE,1651,"Karazhan",8
9/3 23:36:58.403  MAP_CHANGE,814,"Karazhan",-10802.900391,-11190.599609,-1624.225586,-2205.774414`

I did a little looking around and I think it's related to this commit:
https://github.com/DeadlyBossMods/DBM-Unified/commit/35ddef3cc5b6cf6b280914e3c0208c20ecaaf5a0

**Comment by MysticalOS** [comment]
That was done to fix another bug where it was actually ALWAYS logging M+ even if option too do so was disabled.

But you are right the fix broke auto logging when you DID want it to. Putting a fix out for that now.

**Comment by psiklos** [comment]
Thank you for the speedy reply and fix!
