### ISSUE TITLE
says error 2553 id

### ISSUE THREAD

**Issue by lou970** [DeadlyBossMods/DBM-Retail#807]
![WoWScrnShot_091022_151409](https://user-images.githubusercontent.com/103146194/189538056-bd365349-d098-452e-88dd-e376bb931315.jpg)
![WoWScrnShot_091022_151409](https://user-images.githubusercontent.com/103146194/189538064-e77a07bd-45a5-45d2-a5b8-7d5111903cd1.jpg)

**Comment by MysticalOS** [comment]
did you see that error on any pull you weren't resetting boss on? I can see it was only a 6 second pull and it's likely the cause of error was the resetting

**Comment by lou970** [comment]
Yes someone else was resetting the boss during a b.o.e. run articifer is this due to corruption because I did have a power outage during playtime or is it normal?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
