### ISSUE TITLE
On Beta: Message: LibSpecialization: Unknown specId "1467"

### ISSUE THREAD

**Issue by greenstones** [DeadlyBossMods/DBM-Retail#808]
Message: LibSpecialization: Unknown specId "1467"
Time: Mon Sep 19 09:50:01 2022
Count: 1
Stack: LibSpecialization: Unknown specId "1467"
[string "@Interface/AddOns/DBM-Core/Libs/LibSpecialization/LibSpecialization.lua"]:248: in function `RequestSpecialization'
[string "@Interface/AddOns/DBM-Core/Libs/LibSpecialization/LibSpecialization.lua"]:218: in function <...BM-Core/Libs/LibSpecialization/LibSpecialization.lua:160>

Locals: <none>

Get the above error when you first log in on an evoker in beta.

**Comment by MysticalOS** [comment]
Best way to avoid errors on beta, is to actually run latest versions of mod. This will not be an issue once you update DBM

**Comment by greenstones** [comment]
Actually I was running the latest version of the mod on curse: version 9.2.34 unless im mistaken that is the most recent.  I will delete all dbm files and try again to make sure.

**Comment by MysticalOS** [comment]
Double check if it was beta addons folder maybe? might have been installed in PTR or retail and not up to date in beta

**Comment by greenstones** [comment]
Its beta I can give you a screenshot

**Comment by greenstones** [comment]
Took a while to get on - I deleted the folders as well as the wtf info - that cleared it up maybe it had corrupted a older file.
