### ISSUE TITLE
[notification] Failed to detect Fated affix ID 2402

### ISSUE THREAD

**Issue by conetopia** [DeadlyBossMods/DBM-Retail#809]
<DBM> Failed to detect Fated affix after 10 seconds of scanning
Notify DBM authors with this id :2402

LFR - Fated
Reliquary of opulence
Boss 1 Kael'thas rescued

**Comment by MysticalOS** [comment]
What DBM version? Was it a fast wipe or boss reset?

**Comment by conetopia** [comment]
> 

DBM-9.2.34
We just started the Raid, was cleaning trash, and saw that notification as we entered the room/area

**Comment by MysticalOS** [comment]
so kael is still firing buggy engage events, that's not really surprising. DBM thought boss was engaged when it wasn't basiclaly?

**Comment by conetopia** [comment]
> so kael is still firing buggy engage events, that's not really surprising. DBM thought boss was engaged when it wasn't basiclaly?

Probably.
