### ISSUE TITLE
Jailer LUA error: Interface/AddOns/DBM-Sepulcher/TheJailer.lua:642: attempt to compare number with nil

### ISSUE THREAD

**Issue by brittyazel** [DeadlyBossMods/DBM-Retail#817]
When doing the Jailer tonight this error popped up. Not sure what caused it, but it happened in the second phase. My DBM is version 10.0.0

2x Interface/AddOns/DBM-Sepulcher/TheJailer.lua:642: attempt to compare number with nil
[string "@Interface/AddOns/DBM-Sepulcher/TheJailer.lua"]:642: in function `handler'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:928: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:915>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:928: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:915>

Locals:
Skipped (In Encounter)

**Comment by MysticalOS** [comment]
Did you reload ui middle of fight?

**Comment by brittyazel** [comment]
It's possible, I was having LUA errors stopping me from using my actionbars. I can't recall exactly, but I was /reloading throughout the night

**Comment by MysticalOS** [comment]
closing this, as there is really no way to fix it, other than blizzard to fix their crappy 10.0 ui code so users don't have to reload mid combat to cast spells
