### ISSUE TITLE
LUA Error when trying to use Silverdragon's macro - but shows a DBM LUA error

### ISSUE THREAD

**Issue by Wyr3d** [DeadlyBossMods/DBM-Retail#822]
**Describe the bug**

Was attempting to run a rare scan using Silverdragon. It should have done nothing, unless a rare was neary.

Instead it popped up with "You are attempting to run a custom script, blah blah warning blah"

Accepting the script despite warning popped up with the lua error below, that is DBM based. Oddly there is no problem on another account, just this one.

**Do you have an error log of what happened?**

Date: 2022-10-31 17:06:47
ID: 1
Error occured in: AddOn: DBM-Core
Count: 1
Message: Error: AddOn DBM-Core attempted to call a forbidden function (SetAllowDangerousScripts()) from a tainted execution path.
Debug:
   [string "=[C]"]: SetAllowDangerousScripts()
   [string "@..\FrameXML\StaticPopup.lua"]:4165: OnAccept()
   [string "@..\FrameXML\StaticPopup.lua"]:5228: StaticPopup_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
None
AddOns:

**Comment by QartemisT** [comment]
Seems like another DragonFlight taint issue. Isn't much we can do to resolve this sadly.

**Comment by Wyr3d** [comment]
This was on Classic WotLK though, and as I said - it works fine for my main account, just the spare has this problem
