### ISSUE TITLE
Text notification about the beginning / end of the fight

### ISSUE THREAD

**Issue by artazika** [DeadlyBossMods/DBM-Retail#823]
DBM reports in the chat about the beginning / end of the fight of the guild raid groups and at the same time writes "leader's name" guild group instead "the name of the guild" guild group.
<DBM> Mythic-Rigelon was defeated by Nivei's guild group after 4 min 52.25 sec!

Text notification about the beginning / end of the fight

**Do you have an error log of what happened?**
This is not really an interface error, just a notification error

**To Reproduce**
1) Be out of the guild raid
2) See a notification about the beginning / end of a fight in the chat

**Screenshots**
![image](https://user-images.githubusercontent.com/39316666/199101923-fb7d4a04-2b08-42ae-93fa-197be5c82728.png)
![image](https://user-images.githubusercontent.com/39316666/199101958-6311274b-19cf-487f-bc20-f1dd0b4c5137.png)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Nope, also I don't use ElvUI

**Which version of DeadlyBossMods are you using?**
DBM-10.0.0

**Was it working in a previous version? If yes, which was the last good one?**
Yes, before DF it was fine. probably DBM-9.2.37 and lower

**Comment by Molkree** [comment]
@Hollicsh, extra `'s` in both messages, can be removed.

**Comment by artazika** [comment]
> that's intended, maybe not translated properly? It gives the group leaders name not guilds name, cause you don't need guilds name, you know what guild you're in, you want to know WHICH guild group it is when running multiple, thus the raid leaders name.

hm, maybe. I'm used to it, it always wrote the guild name before

**Comment by Hollicsh** [comment]
Omg .. Sorry. I made corrections.

**Comment by MysticalOS** [comment]
it never gave guild name. it'd just say "guild has engaged x" unnamed. but that never made it clear who's group it was when you'd have multiple raids going at once (more common in classic for sure but also high end raids doing split runs on retail).

Adding group leaders name was correction for this. anyways closing issue
