### ISSUE TITLE
Show cut screens on boss kill

### ISSUE THREAD

**Issue by Eswaddica** [DeadlyBossMods/DBM-Retail#824]
Hi, 

I keep getting an error message when killing a boss something like this:

<DBM> Attempted to stop a cut screen

and then i just stand there while everyone else gets a cut screen that furthers the story. How do i stop DBM from stopping the cut screen, i want to see it.

**Comment by QartemisT** [comment]
It looks like you enabled this feature within DBM's settings. If you don't want to skip cutscenes automatically, simply disable it :)

**Comment by Eswaddica** [comment]
Where is the option I've looked everywhere and cant fin it, or anything in the help on these pages.
