### ISSUE TITLE
DBM RegisterEvents Error when entering Heroic Return to Karazhan

### ISSUE THREAD

**Issue by Sluimerstand** [DeadlyBossMods/DBM-Retail#826]
**To Reproduce**
Enter Heroic Return to Karazhan.

**Screenshots**
![image](https://user-images.githubusercontent.com/29845810/201532903-b09502fb-40ad-4633-98a8-c58ad81ea10a.png)

**Which version of DeadlyBossMods are you using?**
10.0.1 (2022/11/08)

**Comment by QartemisT** [comment]
Hi there,

This is in preperation for the Tuesday build, it can be safely ignored :)
