### ISSUE TITLE
DBM-StatusBarTimers Bug in Tomb of Sargeras

### ISSUE THREAD

**Issue by ljlevend** [DeadlyBossMods/DBM-Retail#827]
**Describe the bug**
The following bug occurred during the Sisters of the Moon fight in Tomb of Sargeras on Mythic difficulty. I was doing it solo on a Demon Hunter.

**Do you have an error log of what happened?**
Message: Interface/AddOns/DBM-StatusBarTimers/DBT.lua:810: bad argument #1 to 'SetValue' (must be a finite number - Usage: self:SetValue(value))
Time: Fri Nov 18 23:34:04 2022
Count: 1
Stack: Interface/AddOns/DBM-StatusBarTimers/DBT.lua:810: bad argument #1 to 'SetValue' (must be a finite number - Usage: self:SetValue(value))
[string "@Interface/AddOns/DBM-StatusBarTimers/DBT.lua"]:589: in function <Interface/AddOns/DBM-StatusBarTimers/DBT.lua:586>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/DBM-TombofSargeras/SistersoftheMoon.lua"]:397: in function `handler'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:930: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:917>

Locals: self = <table> {
 GetBar = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:567
 SetAnnounceHook = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:597
 numBars = 7
 ShowMovableBar = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:489
 Options = <table> {
 }
 announceHook = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6441
 GetSkins = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:1173
 CopyProfile = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:416
 ResetSkin = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:1160
 SetOption = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:508
 ApplyProfile = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:399
 SetSkin = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:1136
 UpdateBar = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:586
 LoadOptions = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:347
 DeleteProfile = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:445
 RegisterSkin = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:1117
 DefaultOptions = <table> {
 }
 CreateBar = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:247
 UpdateBars = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:601
 ApplyStyle = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:626
 SavePosition = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:632
 ShowTestBars = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:643
 Rearrange = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:458
 CreateProfile = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:376
 GetBarIterator = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:559
 CancelBar = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:575
 bars = <table> {
 }
 AddDefaultOptions = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:150
 CreateDummyBar = <function> defined @Interface/AddOns/DBM-StatusBarTimers/DBT.lua:542
}
id = "Timer239379nextcount"
elapsed = 0
totalTime = 0
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
  = true
  = true
  = true
  = true
  = true
  = true
  = true
}
(for control) = <table> {
 totalTime = 0
 lastUpdate = 52612.734000
 movePoint = "TOP"
 moveAnchor = Frame {
 }
 moveOffsetX = 818.333183
 curTime = 52576.615000
 owner = <table> {
 }
 moveElapsed = 0
 countdownMax = 4
 countdown = 1
 colorType = 3
 moveOffsetY = 383.888794
 delta = 0.050000
 timer = 54
 frame = DBT_Bar_2 {
 }
 id = "Timer239379nextcount"
}
bar = <table> {
 totalTime = 0
 lastUpdate = 52612.734000
 movePoint = "TOP"
 moveAnchor = Frame {
 }
 moveOffsetX = 818.333183
 curTime = 52576.615000
 owner = <table> {
 }
 moveElapsed = 0
 countdownMax = 4
 countdown = 1
 colorType = 3
 moveOffsetY = 383.888794
 delta = 0.050000
 timer = 54
 frame = DBT_Bar_2 {
 }
 id = "Timer239379nextcount"
}

**To Reproduce**
Unknown

**Screenshots**
None

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, but I don't use ElvUI.

**Which version of DeadlyBossMods are you using?**
Most recent version.

**Was it working in a previous version? If yes, which was the last good one?**
Unknown.

**Additional context**

**Comment by Revnn** [comment]
Happens on normal as well.

**Comment by Revnn** [comment]
Not fixed.

**Comment by MysticalOS** [comment]
You didn't update the legion mods? or you did and it still didn't go away? I can't see a possible way the error would have continued in update

**Comment by Revnn** [comment]
![image](https://user-images.githubusercontent.com/22274813/209005974-66fc4131-5174-48ab-957b-41ffc607f9b8.png)

I use curse to update everything.
Next week when i go inside i'll copy my error, might be different from this one

**Comment by Zxkarie** [comment]
Not fixed. I posted #837 before you locked it.
My kill was 23seconds long and it spammed 433 times.

433x DBM-StatusBarTimers/DBT.lua:810: bad argument #1 to 'SetValue' (must be a finite number - Usage: self:SetValue(value))
[string "=[C]"]: in function `SetValue'
[string "@DBM-StatusBarTimers/DBT.lua"]:810: in function `Update'
[string "@DBM-StatusBarTimers/DBT.lua"]:653: in function `SetTimer'
[string "@DBM-StatusBarTimers/DBT.lua"]:589: in function <DBM-StatusBarTimers/DBT.lua:586>
[string "=(tail call)"]: ?
[string "@DBM-TombofSargeras/SistersoftheMoon.lua"]:397: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:931: in function <DBM-Core/DBM-Core.lua:918>

Locals:
Skipped (In Encounter)

**Comment by MysticalOS** [comment]
You're clearly not understanding, Update the LEGION mods, not core. that line number still correlates to the unfixed out of date legion mods

This issue was fixed, you didn't download the fix
