### ISSUE TITLE
Alert spam Magma Fist at Neltharus

### ISSUE THREAD

**Issue by vicketernal** [DeadlyBossMods/DBM-Retail#830]
I would like to report a DBM 10.0.4 bug, is spamming multiple mensages of frontal attack [https://www.wowhead.com/beta/spell=372311/magma-fist](url)
check the screenshot

https://imgur.com/a/xlXAyRY

**Comment by Molkree** [comment]
I think it was fixed in this commit https://github.com/DeadlyBossMods/DBM-Dungeons/commit/ed8f33262808aa430cf6b6144c41482cc561cfdf so the next release of DBM-Dungeons should include it. And it's already included in the latest alpha of DBM-Dungeons.
