### ISSUE TITLE
Halls of Infusion Error

### ISSUE THREAD

**Issue by Niyuni** [DeadlyBossMods/DBM-Retail#831]
Since update to latest 
1.

2x ...ragonflight/HallsofInfusion/HallsofInfusionTrash.lua:10: attempt to perform arithmetic on a string value
[string "@DBM-Party-Dragonflight/HallsofInfusion/HallsofInfusionTrash.lua"]:10: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@DBM-Core/DBM-Core.lua"]:3548: in function `LoadMod'
[string "@DBM-Core/DBM-Core.lua"]:3491: in function `LoadModsOnDemand'
[string "@DBM-Core/DBM-Core.lua"]:3429: in function `func'
[string "@DBM-Core/modules/Scheduler.lua"]:171: in function <DBM-Core/modules/Scheduler.lua:162>

Locals:
mod = <table> {
 timers = <table> {
 }
 categorySort = <table> {
 }
 SyncThreshold = 8
 modId = "DBM-Party-Dragonflight"
 groupSpells = <table> {
 }
 zones = <table> {
 }
 revision = 20221204033441
 Options = <table> {
 }
 DefaultOptions = <table> {
 }
 id = "HallsofInfusionTrash"
 isTrashMod = true
 addon = <table> {
 }
 specwarns = <table> {
 }
 groupOptions = <table> {
 }
 iconRestore = <table> {
 }
 optionCategories = <table> {
 }
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 subTab = 8
}
L = <table> {
 name = "Halls of Infusion Trash"
}
(*temporary) = <function> defined @DBM-Core/DBM-Core.lua:1094
(*temporary) = <table> {
 timers = <table> {
 }
 categorySort = <table> {
 }
 SyncThreshold = 8
 modId = "DBM-Party-Dragonflight"
 groupSpells = <table> {
 }
 zones = <table> {
 }
 revision = 20221204033441
 Options = <table> {
 }
 DefaultOptions = <table> {
 }
 id = "HallsofInfusionTrash"
 isTrashMod = true
 addon = <table> {
 }
 specwarns = <table> {
 }
 groupOptions = <table> {
 }
 iconRestore = <table> {
 }
 optionCategories = <table> {
 }
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 subTab = 8
}
(*temporary) = "SPELL_CAST_START 390290 374080 375351 375348 375327 375384 374563"
(*temporary) = "SPELL_AURA_APPLIED 374724"
(*temporary) = 20221204033441
(*temporary) = "number"
(*temporary) = 4
(*temporary) = 3
(*temporary) = 34
(*temporary) = 41
(*temporary) = 20221204033441
(*temporary) = 20220000000000
(*temporary) = 2022
(*temporary) = 12
(*temporary) = 4
(*temporary) = 3
(*temporary) = 34
(*temporary) = "attempt to perform arithmetic on a string value"

and 2.
4x DBM-Party-Dragonflight/HallsofInfusion/HallsofInfusionTrash.lua:1 (null)

**Comment by MysticalOS** [comment]
This was already fixed in alpha, Closing as it'll be included in next release
