### ISSUE TITLE
LUA error when zoning into raid

### ISSUE THREAD

**Issue by raysmith59** [DeadlyBossMods/DBM-Retail#834]
2x .../DBM-VaultoftheIncarnates/RaszageththeStormEater.lua:82: attempt to call method 'NewFadedAnnounce' (a nil value)
[string "@DBM-VaultoftheIncarnates/RaszageththeStormEater.lua"]:82: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@DBM-Core/DBM-Core.lua"]:3552: in function `LoadMod'
[string "@DBM-Core/DBM-Core.lua"]:3495: in function `LoadModsOnDemand'
[string "@DBM-Core/DBM-Core.lua"]:3433: in function `func'
[string "@DBM-Core/modules/Scheduler.lua"]:171: in function <DBM-Core/modules/Scheduler.lua:162>

Locals:
mod = <table> {
 timers = <table> {
 }
 categorySort = <table> {
 }
 instanceId = 1200
 modelId = 103255
 SyncThreshold = 8
 modId = "DBM-VaultoftheIncarnates"
 groupSpells = <table> {
 }
 findFastestComputer = <table> {
 }
 inCombatOnlyEvents = <table> {
 }
 combatInfo = <table> {
 }
 zones = <table> {
 }
 revision = 20221208063305
 Options = <table> {
 }
 DefaultOptions = <table> {
 }
 id = "2499"
 hotfixNoticeRev = 20221124000000
 usedIcons = <table> {
 }
 encounterId = 2607
 addon = <table> {
 }
 groupOptions = <table> {
 }
 specwarns = <table> {
 }
 iconRestore = <table> {
 }
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 optionCategories = <table> {
 }
}
L = <table> {
 negative = "negative"
 name = "Raszageth the Storm-Eater"
 positive = "positive"
}
warnPhase = <table> {
 type = "stagechange"
 spellId = 0
 option = "announce0stagechange"
 color = <table> {
 }
 text = "%s"
 announceType = "stagechange"
 combinedcount = 0
 mod = <table> {
 }
 combinedtext = <table> {
 }
 sound = 2
 icon = 136116
 spellName = "Unknown"
}
specWarnGTFO = <table> {
 voiceOptionId = "Voice388115"
 hasVoice = 8
 spellId = 388115
 icon = 4640481
 option = "SpecWarn388115gtfo"
 text = "%s damage - move away"
 flash = 1
 combinedcount = 0
 mod = <table> {
 }
 announceType = "gtfo"
 type = "gtfo"
 combinedtext = <table> {
 }
 sound = true
 spellName = "Lightning Devastation"
}
warnStaticCharge = <table> {
 type = "target"
 spellId = 381615
 option = "announceother381615target"
 color = <table> {
 }
 text = "Static Charge on >%s<"
 announceType = "target"
 combinedcount = 0
 mod = <table> {
 }
 noFilter = true
 combinedtext = <table> {
 }
 sound = 1
 icon = 237587
 spellName = "Static Charge"
}
warnLightningStrike = <table> {
 type = "count"
 spellId = 376126
 option = "announce376126count"
 color = <table> {
 }
 text = "Lightning Strikes (%s)"
 announceType = "count"
 combinedcount = 0
 mod = <table> {
 }
 combinedtext = <table> {
 }
 sound = 1
 icon = 135990
 spellName = "Lightning Strikes"
}
warnElectricScales = <table> {
 type = "count"
 spellId = 381249
 option = "announce381249count"
 color = <table> {
 }
 text = "Electric Scales (%s)"
 announceType = "count"
 combinedcount = 0
 mod = <table> {
 }
 combinedtext = <table> {
 }
 sound = 1
 icon = 463562
 spellName = "Electric Scales"
}
specWarnHurricaneWing = <table> {
 voiceOptionId = "Voice377612"
 hasVoice = 2
 spellId = 377612
 icon = 4640499
 option = "SpecWarn377612count"
 text = "Hurricane Wing! (%s)"
 flash = 2
 combinedcount = 0
 mod = <table> {
 }
 announceType = "count"
 type = "count"
 combinedtext = <table> {
 }
 sound = true
 spellName = "Hurricane Wing"
}
specWarnStaticCharge = <table> {
 voiceOptionId = "Voice381615"
 hasVoice = 2
 spellId = 381615
 icon = 237587
 option = "SpecWarn381615youpos"
 text = "Bomb (Position: %s) on you"
 flash = 1
 combinedcount = 0
 mod = <table> {
 }
 announceType = "youpos"
 type = "youpos"
 combinedtext = <table> {
 }
 sound = true
 spellName = "Bomb"
}
yellStaticCharge = <table> {
 mod = <table> {
 }
 spellId = 381615
 option = "Yell381615shortposition"
 text = "{rt%1$d}Bomb %2$d"
 yellType = "shortposition"
}
yellStaticChargeFades = <table> {
 mod = <table> {
 }
 spellId = 381615
 option = "Yell381615iconfade"
 text = "{rt%2$d}%1$d"
 yellType = "iconfade"
}
specWarnVolatileCurrent = <table> {
 voiceOptionId = "Voice388643"
 hasVoice = 2
 spellId = 388643
 icon = 136099
 option = "SpecWarn388643moveawaycount"
 text = "Volatile Current (%s) - move away from others"
 flash = 2
 combinedcount = 0
 mod = <table> {
 }
 announceType = "moveawaycount"
 type = "moveawaycount"
 combinedtext = <table> {
 }
 sound = true
 spellName = "Volatile Current"
}
specWarnBurst = <table> {
 voiceOptionId = "Voice388635"
 hasVoice = 2
 spellId = 388635
 icon = 1717108
 option = "SpecWarn388635interruptcount"
 text = "Burst - interrupt >%s<! (%d)"
 flash = 1
 combinedcount = 0
 mod = <table> {
 }
 announceType = "interruptcount"
 type = "interruptcount"
 combinedtext = <table> {
 }
 sound = true
 spellName = "Burst"
}
specWarnElectrif

**Comment by MysticalOS** [comment]
already fixedd, but it might be a day or two til i push it, i'm way behind updating rest of bosses cause I've spent 3 hours on just sennarth
