### ISSUE TITLE
LUA error when I joined a raid for the world boss

### ISSUE THREAD

**Issue by raysmith59** [DeadlyBossMods/DBM-Retail#835]
I'm guessing this has been fixed as well but just in case...

2x DBM-DragonIsles/Liskanoth.lua:1: DBM:NewMod(): Mod names are used as IDs and must therefore be unique.
[string "=[C]"]: in function `error'
[string "@DBM-Core/DBM-Core.lua"]:6602: in function `NewMod'
[string "@DBM-DragonIsles/Liskanoth.lua"]:1: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@DBM-Core/DBM-Core.lua"]:3552: in function `LoadMod'
[string "@DBM-Core/DBM-Core.lua"]:3600: in function <DBM-Core/DBM-Core.lua:3590>
[string "@DBM-Core/DBM-Core.lua"]:3619: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:931: in function <DBM-Core/DBM-Core.lua:918>

Locals:
(*temporary) = "DBM:NewMod(): Mod names are used as IDs and must therefore be unique."

**Comment by MysticalOS** [comment]
Yep, fixed already
