### ISSUE TITLE
Error when targeting new World Boss

### ISSUE THREAD

**Issue by efenzl** [DeadlyBossMods/DBM-Retail#836]
Got this message when targeting the new world boss Basrikron

Message: Interface/AddOns/DBM-DragonIsles/Liskanoth.lua:1: DBM:NewMod(): Mod names are used as IDs and must therefore be unique.
Time: Wed Dec 14 15:47:48 2022
Count: 1
Stack: Interface/AddOns/DBM-DragonIsles/Liskanoth.lua:1: DBM:NewMod(): Mod names are used as IDs and must therefore be unique.
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:3552: in function `LoadMod'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:3600: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:3590>
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:3615: in function `handler'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:931: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:918>

Locals: (*temporary) = "DBM-DragonIsles"
(*temporary) = <function> defined =[C]:-1

**Comment by MysticalOS** [comment]
This was fixed yesterday and a new release for it was pushed out 8 hours ago. please check for updates before reporting bugs
