### ISSUE TITLE
LUA error spam.

### ISSUE THREAD

**Issue by Zxkarie** [DeadlyBossMods/DBM-Retail#837]
Been running some older raids, have all the expansion modules. Keep getting this error. Noticed it does it more on the Sisters Of The Moon encounter in Tomb of Sarg. 

192x DBM-StatusBarTimers/DBT.lua:810: bad argument #1 to 'SetValue' (must be a finite number - Usage: self:SetValue(value))
[string "=[C]"]: in function `SetValue'
[string "@DBM-StatusBarTimers/DBT.lua"]:810: in function `Update'
[string "@DBM-StatusBarTimers/DBT.lua"]:653: in function `SetTimer'
[string "@DBM-StatusBarTimers/DBT.lua"]:589: in function <DBM-StatusBarTimers/DBT.lua:586>
[string "=(tail call)"]: ?
[string "@DBM-TombofSargeras/SistersoftheMoon.lua"]:397: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:931: in function <DBM-Core/DBM-Core.lua:918>

Locals:
Skipped (In Encounter)

**Comment by MysticalOS** [comment]
duplicate of https://github.com/DeadlyBossMods/DBM-Retail/issues/827

**Comment by Zxkarie** [comment]
And?
There's no resolution.
