### ISSUE TITLE
No Bar Timers Showing

### ISSUE THREAD

**Issue by OdessaGrimaldus** [DeadlyBossMods/DBM-Retail#843]
**Describe the bug**
Timers for boss mechanics of both new dungeons and old are not showing, despite being active in the addon

**Do you have an error log of what happened?**
I am not receiving and error for this

**To Reproduce**
Simply do a boss fight of any kind currently, and nothing will show as warnings of oncoming mechanics as bar timers.

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I have tried with only DBM and it's plugs required for said dungeon/boss-fight active and still these bar timers do not show.

**Which version of DeadlyBossMods are you using?**
I am using the most current version "DBM-10.0.11-11-ga103501.zip" - but have been experiencing this issue the entirety of Dragonflight, since the expansion release that none of these new dungeons or dungeons brought back as Mythic+ dungeons have their mechanic timers active.

**Was it working in a previous version? If yes, which was the last good one?**
I can't really say, since it is all the new content that the issue is coming about in.. Back with Shadowlands the "DBM-10.0.2.zip" release was still working, but again that was with content of Shadowlands which this issue doesn't pertain to.

**Additional context**

**Comment by MysticalOS** [comment]
Dungeons are not built into DBM -Core download, you need to download DBM-Dungeons in addition to core
