### ISSUE TITLE
Court of Stars clues not in chat

### ISSUE THREAD

**Issue by rebeccacarf** [DeadlyBossMods/DBM-Retail#846]
**Describe the bug**
In Court of Stars M+ the clues to help identify the spy are not shown in party chat even though I selected the option in the addon settings. I do see the clues written in a box that I can see, but don't share them with my group.

**Do you have an error log of what happened?**
I don't have an error log for this.

**To Reproduce**
1. Turn on "Also send hints to chat" with "Help identify the spy" enabled (was enabled by default).
2. Do Court of Stars M+.
3. Do not see clues in party chat.

**Screenshots**
![image](https://user-images.githubusercontent.com/121484716/209639776-42bd1d5b-afbe-4a60-85da-173b3e6e66ee.png)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I don't use any addons of this type, just default Blizzard UI.

**Which version of DeadlyBossMods are you using?**
Last used with this problem was [10.0.12](https://github.com/DeadlyBossMods/DBM-Retail/tree/10.0.12) (2022-12-23)

**Was it working in a previous version? If yes, which was the last good one?**
I don't know, I just recently tried to enable the option.

**Additional context**

**Comment by MysticalOS** [comment]
Closing duplicate

**Comment by Molkree** [comment]
@rebeccacarf, you can track this issue here https://github.com/DeadlyBossMods/DBM-Dungeons/issues/77
