### ISSUE TITLE
Meteor Axe timer correction - Heroic

### ISSUE THREAD

**Issue by mechiah** [DeadlyBossMods/DBM-Retail#850]
**Describe the bug**
Meteor Axe timer in-game consistently early. 

Compared all our pulls on this boss, and spot checked some public logs unrelated to us, and found these times for **cast completion**:
0m35s Meteor Axe 1
1m29s Meteor Axe 2
2m22s Meteor Axe 3
3m15s Meteor Axe 4
4m09s Meteor Axe 5
5m02s Meteor Axe 6

Indicating approximately 30s for first start, then , approximately 45s CD after completion for subsequent casts, plus or minus a second or two.

Sample logs:
https://www.warcraftlogs.com/reports/BrF4NR3MbdPXGwqj#fight=13&type=casts&hostility=1&ability=374038&view=events
https://www.warcraftlogs.com/reports/LwTQa3bBPDjpKF1H#fight=17&type=casts&view=events&hostility=1&ability=374038

I looked at PrimalistCouncil.lua and found
Ln 86 
`local timerMeteorAxeCD = mod:NewCDCountTimer(39.1, 374043, nil, nil, nil, 3)`
and
Ln 160 
`timerMeteorAxeCD:Start(23-delay, 1)`

I only have half ass understanding of your boss LUAs so I'm going to YOLO those values to ~~49.1~~ 44.9 and 30, respectively, for tonight's raid. Then pray.

**Comment by MysticalOS** [comment]
Thanks, not sure when this changed, coulda been weeks ago but I only looked at heroic week 1 and that's it unless blizzard announces changes or users report them. neither happened til now :\

I have to do 4th release of day anyways to fix something else so this fix will be in that.
