### ISSUE TITLE
Throne of Thunder - Council of Elders - DMB-StatusBarTimers DBT SetValue Error

### ISSUE THREAD

**Issue by Malivil** [DeadlyBossMods/DBM-Retail#851]
**Describe the bug**
When starting the Council of Elders fight, an error window continuously throughout the fight until the final boss was killed.

**Do you have an error log of what happened?**
> Message: Interface/AddOns/DBM-StatusBarTimers/DBT.lua:810: bad argument #1 to 'SetValue' (must be a finite number - Usage: self:SetValue(value))
Time: Wed Jan 11 22:24:26 2023
Count: 592
Stack: Interface/AddOns/DBM-StatusBarTimers/DBT.lua:810: bad argument #1 to 'SetValue' (must be a finite number - Usage: self:SetValue(value))
[string "=[C]"]: in function `SetValue'
[string "@Interface/AddOns/DBM-StatusBarTimers/DBT.lua"]:810: in function `Update'
[string "@Interface/AddOns/DBM-StatusBarTimers/DBT.lua"]:169: in function <Interface/AddOns/DBM-StatusBarTimers/DBT.lua:163>

> Locals: (*temporary) = DBT_Bar_4Bar {
 0 = <userdata>
}
(*temporary) = Infinite
(*temporary) = "must be a finite number - Usage: self:SetValue(value)"

**To Reproduce**
1. Go to Throne of Thunder on the Isle of Thunder in Pandaria
2. Fight through to the Council of Elders
3. Start the Council of Elders fight
-->

**Screenshots**
N/A

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
10.0.19

**Was it working in a previous version? If yes, which was the last good one?**
Unsure

**Additional context**

**Comment by QartemisT** [comment]
Fixed by <https://github.com/DeadlyBossMods/DBM-MoP/commit/3d1d9c3068afcea77e69693bad68cd4f4f938e83>

Since stacktrace didn't provide detailed information, going to assume you were either out of date before r151 for DBM-MoP, or the above issue fixes it (check alpha)

**Comment by Malivil** [comment]
I'm on r151 of DMB-MoP, but I'll check again with the update (or the alpha, if an update isn't out) next week

**Comment by Malivil** [comment]
Just ran the encounter again with MoP alpha and the error is gone. Thanks =)
