### ISSUE TITLE
DBM Randomly starting breaktime

### ISSUE THREAD

**Issue by Wraiven** [DeadlyBossMods/DBM-Retail#852]
So DBM is randomly sending starting breaktime messages and starting a break time.. it spammed it like 5 times in a row from one player and then it started me sending it. I dint even know how to turn it off, i had to google.

**Comment by MysticalOS** [comment]
someone else probably trolled and spammed a break timer, when it shows yourself sending it, it sounds like you reloaded ui. if you have an active break timer during logout or ui reload, DBM remembers it and recovers it, but with you as sender. 

Ultimately I can't prevent trolling of feature without breaking it entirely. Only players with assist can send it so if you have a troll with assist they should probably be demoted.

**Comment by Wraiven** [comment]
gotcha ty! Had no idea it wasnt a bug

**Comment by MysticalOS** [comment]
No problem, i'd rather a person ask then be unsure and silent, that leads to many actual bugs going under reported. Always feel encouraged to. ask.
