### ISSUE TITLE
DBM keeps resetting bar skin to "Addonskins"

### ISSUE THREAD

**Issue by deadcode0815** [DeadlyBossMods/DBM-Retail#853]
**Describe the bug**
DBM keeps resetting bar skin to "Addonskins" after reloading ui (logout/login, reloadui)

**Do you have an error log of what happened?**
nope :(

**To Reproduce**
import raid ability timeline (https://wago.io/RaidAbilityTimeline)
set using Jods_Raid_Ability_Timeline_Skin in DBM

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
only installed addons:
DBM (retail)
AddonSkins
WeakAuras

- I have done a total reset (clean install) (/console cvar_default, deleting WTF folder)

**Which version of DeadlyBossMods are you using?**
most current version: 10.0.20

**Comment by QartemisT** [comment]
Go into the AddOnSkins settings, and disable the DBM module :)
