### ISSUE TITLE
Missing Timer on Sennarth Mythic

### ISSUE THREAD

**Issue by Jaidy88** [DeadlyBossMods/DBM-Retail#855]
**Describe the bug**
Unfortunately, there is no timer for Gusting Rime in Sennarth Mythic. In the options you can see that there should be a timer and also a warning, but unfortunately this does not happen. 

**Screenshots**
https://gyazo.com/834537c89089252925e955fc42dc153e
https://gyazo.com/31b05d672dc3aa8bc367c96becb657aa

Stream: https://www.twitch.tv/videos/1722263147?t=03h25m57s  (left side big bars, right side next timers)

**Which version of DeadlyBossMods are you using?**
10.0.22

**Additional context**
It would be great to see when the next winds come so that e.g. divine hymn does not have to be canceled. is it because in the logs are another spell id then in dbm?

**Comment by MysticalOS** [comment]
Forgot to remove it actually. it doesn't need a timer or warning, it's just a passive mechanic that's part of the movements. there is no timer or alert needed for this. deleting those options and closing this.
