### ISSUE TITLE
Broodkeeper Marking only Marks One Mage

### ISSUE THREAD

**Issue by EvanMichaels** [DeadlyBossMods/DBM-Retail#856]
Raid noted this when using in Mythic tonight. I looked at the code and noticed this line here:

https://github.com/DeadlyBossMods/DBM-Retail/blob/d1ba7549f27c0de75dfd8a21f312ac23ce7351b7/DBM-VaultoftheIncarnates/BroodkeeperDiurna.lua#L258

This appears incorrect and should be self.vb.mageIcon > 3 most likely? As the Mages are configured to use marks 4-6, defaulting to 6 and decrementing on each mob.

**Comment by MysticalOS** [comment]
Good catch, thanks for report. pushing fix out now

**Comment by EvanMichaels** [comment]
No problem, thanks for looking at it so quickly!
