### ISSUE TITLE
Marking Bug Broodkeeper

### ISSUE THREAD

**Issue by Bediko** [DeadlyBossMods/DBM-Retail#860]
Heyho,
there is a bug with the marking option on the stormbringers during the encounter. In the add groups between 3:30 and 3:45 are spawning 2 stormbringers in separate spawns. The problem is now that DBM marks the first stormbringer with a skull when it casts and then marks the second stormbringer when it casts with a skull again leaving the first one without any mark which kinda sucks with Interrupt weakauras that look for specific marks.  I would expect that the second stormbringer gets the cross.

I hope that the description is accurate enough to work with it. Keep up the good work :)

**Comment by MysticalOS** [comment]
I can change how this is handled. the current code only uses diff icons if they spawn together but didn't consider that one might still be alive from a prevous set in the smaller add timing windows. I'll switch it to just a logical alternating icon setup.
