### ISSUE TITLE
Thunder Stomp Timer in M+ Keys

### ISSUE THREAD

**Issue by awcarr** [DeadlyBossMods/DBM-Retail#863]
**Describe the bug**
In m+ I continually get a thundering stomp timer with latest DBM.  It seems to be somewhat aligned with thundering, but not quite.

**Do you have an error log of what happened?**
No not an error.

**To Reproduce**
Install latest DBM
Go into a key.

**Screenshots**
I will try to add one next time I am in a key.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.
**Which version of DeadlyBossMods are you using?**
10.0.3
**Was it working in a previous version? If yes, which was the last good one?**
The version before the latest one.
**Additional context**
I know it is DBM because I can disable m+ affix notifications and it goes away.

**Comment by MysticalOS** [comment]
It's the thundering timer, and it should lineup to thundering within about 5sec, usually within 1sec of the visuals changing and lighting strikes occurring (which happens 4 seconds before charges go out).

The timer name is a bug though that's fixed in next update. it won't say stomp anymore
