### ISSUE TITLE
Global Profile - One Profile For All

### ISSUE THREAD

**Issue by HDMOVIESOURCE** [DeadlyBossMods/DBM-Retail#870]
Hi,

Is it possible to use a better profile system that is easier to use and understand? Right now we have a profile system for the size, placement, and fonts for announcements, bars, and bar colors. Thats great. But, using a profile for the boss options is a mess, (in my opinion).

My suggestion is to have 2 options.
**OPTION 1 -** (In Profiles) Have the ability to use the bar system as one profile and include an option to create a profile for boss mods also. So, whenever you make an adjustment to either one of the profiles it's reflected on an alt also if they are using that profile.

**WHY?** Right now, the profile system is good, but knowing what boss mod profile you're on is impossible, why? Because it actually doesn't show you what profile you're using. So creating profiles for bars and icons, and another profile for boss mods will completely fix that. Right now I get on my main bear tank where I've adjusted things to track and affixes, looks great, then I get on my brewmaster and it's tracking a million things and it's not intuitive that the boss mods are using a completely different profile to my current saved profile. Having 2 profiles in the profiles section would clear up this mess, and make it easier to run a healer profile, DPS profile, and Tank profile.

**OPTION 2 -** (That I'd also like to include) Check option, and UI will reload after being checked. All options and settings are created in a single profile. Meaning if I make boss mods changes on profile A, and my alt uses profile A, those settings will also be changed. For me personally, I want a single profile where if I adjust something on my alt using profile A I then see it on my bear tank when using profile A. But, I also think people want the option to create healer, Tank, and DPS profiles.

**WHY?** Right now you don't even know what profile that's selected for the boss mods. A player it's unintuitive and I think a mess. If you could all players to clear up this, and allow us to create either 2 profiles and or use a single global profile that control both boss mods and bars settings it would be so much better.

I seriously think this needs to happen to seriously improve DBM.

Thanks for listening, I hope this provides good feedback.

**Comment by MysticalOS** [comment]
Closing this as it already has an open issue here:
https://github.com/DeadlyBossMods/DBM-Unified/issues/6

**Comment by HDMOVIESOURCE** [comment]
Okay, thank you.

**Comment by MysticalOS** [comment]
if any of that feedback is missing from there feel free to add it to that issue
