### ISSUE TITLE
On council it says to spread when blizzard is coming out.

### ISSUE THREAD

**Issue by gotex007** [DeadlyBossMods/DBM-Retail#871]
I don't think that's an accurate voice alert to use when blizzard happens as there is no reason to spread.

**Comment by MysticalOS** [comment]
`		specWarnPrimalBlizzard:Show(self.vb.blizzardCast)
		if self:IsHard() then
			specWarnPrimalBlizzard:Play("scatter")--Range 3
		else
			specWarnPrimalBlizzard:Play("aesoon")--Just aoe damage, spread mechanic disabled
		end`

https://www.wowhead.com/spell=373059/primal-blizzard

it has a 3 yard splash damage on heroic and mythic.

**Comment by MysticalOS** [comment]
Odd, journal doesn't mention this heroic/mythic only mechanic anymore. I wonder if they removed it at some point and forgot to update tooltip. it was there when mod was originally made though. I guess I can just assume it's gone and make all difficulties do the aesoon voice
