### ISSUE TITLE
DBM RegisterEvents Error

### ISSUE THREAD

**Issue by rlaqjatl** [DeadlyBossMods/DBM-Retail#879]
**Describe the bug**

DBM RegisterEvents Error: 409492 spell id does not exist!
DBM RegisterEvents Error: 408805spell id does not exist!
DBM RegisterEvents Error: 408556spell id does not exist!

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
that can be safetly ignored in this case
