### ISSUE TITLE
Lua error on yogg all of the sudden

### ISSUE THREAD

**Issue by seskobrodo** [DeadlyBossMods/DBM-Retail#881]
Started getting this error on yogg 25 man WOTLK:
![image](https://user-images.githubusercontent.com/75147266/231913893-fbd46108-9b3a-4d80-911f-77b19956ab1e.png)

**Comment by MysticalOS** [comment]
Did you reload UI in middle of fight for some reason? Not much i can' do about this error if you do that. conditionals like what phase you're in are set on the pull and on phase changes and if you reload UI middle of fight you erase those varaibles. they are eventually recovered from other players but if those conditionals are needed BEFORE recovery completes (can take up to 10 seconds), the whole mod breals

**Comment by MysticalOS** [comment]
I implimented new code that'd avoid error but not actually fix core issue, ie if you reload mid fight it'll still break timers/stage detections sometimes. like you might get portal timers in stage 3 cause you reloaded mid fight and mod doesn't know it's stage 3, BUT it'll fail silently now.
