### ISSUE TITLE
EchoofNeltharion.lua:221: DBM-InfoFrame: Unsupported event

### ISSUE THREAD

**Issue by Ookami313** [DeadlyBossMods/DBM-Retail#886]
**Describe the bug**
Fighting Normal Echo of Neltharion. During the third(?) phase when the portals appear an error kept occurring each time the portals appeared. I'm guessing a little at the moment because the errors occurred during the fight and I was mostly paying attention to the fight than when the error happened.

**Do you have an error log of what happened?**
11x DBM-Aberrus/EchoofNeltharion.lua:221: DBM-InfoFrame: Unsupported event
[string "=[C]"]: ?
[string "@DBM-Core/DBM-InfoFrame.lua"]:1155: in function `Show'
[string "@DBM-Aberrus/EchoofNeltharion.lua"]:221: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:975: in function <DBM-Core/DBM-Core.lua:962>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:975: in function <DBM-Core/DBM-Core.lua:962>

Locals:
Skipped (In Encounter)

**To Reproduce**
1. Go to Echo of Neltharion
2. Start fight
3. advance to last phase when portals and adds appear.
-->

**Screenshots**
None

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?** 
10.1.2

**Was it working in a previous version? If yes, which was the last good one?**
Not sure, just started Abberus today. :)

**Additional context**

**Comment by MysticalOS** [comment]
Thanks for report, will be fixed in next commit (nelth mod is being updated with other stuff at same time)
