### ISSUE TITLE
Random error that I wasnt getting before

### ISSUE THREAD

**Issue by axc450** [DeadlyBossMods/DBM-Retail#888]
On every reload/login:
![image](https://github.com/DeadlyBossMods/DBM-Retail/assets/30942843/f02ce1e5-86d0-4576-ab00-0c63e59c9082)

**Comment by MysticalOS** [comment]
It was a bug with the force disable (for being too out of date). It's fixed already, but you don't have fix, because you're too out of date. there was a major patch last week, you need to update DBM to latest version to not only fix this but make it functional again with new patch and new content.

**Comment by axc450** [comment]
Is this not the current version? Or is it a curse bug? Sorry for being a pain! :D 
![image](https://github.com/DeadlyBossMods/DBM-Retail/assets/30942843/c34f387c-a887-4da0-8e46-f803cffb6537)

**Comment by axc450** [comment]
Oh I had it set to PTR - please close

**Comment by MysticalOS** [comment]
Yeah I was gonna suggest maybe game version was miselected, Glad you resolved
