### ISSUE TITLE
Aberrus - Assault of the Zaqali - warning being spammed

### ISSUE THREAD

**Issue by p3lim** [DeadlyBossMods/DBM-Retail#889]
**Describe the bug**

During this fight, phase 2 (add phase) when I get targeted by the line (I think its name is Blazing Spear?), DBM warnings spam tens of times per second for as long as it's being cast, resulting in audio overload and chat warnings for spam.

**Do you have an error log of what happened?**

No errors, but audio spam and this in chat:
![image](https://github.com/DeadlyBossMods/DBM-Retail/assets/26496/5c47ce03-01dd-4915-916e-0dc72791823d)

**To Reproduce**

Do the boss with DBM enabled (on heroic if that matters)

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of DeadlyBossMods are you using?**

r78

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
Are you sure it's DBM? nothing in that screen shot shows DBM? what sound are you hearing repeatedly? What dbm message?

**Comment by MysticalOS** [comment]
Nevermind found likely culprit, will push a new fix out

**Comment by p3lim** [comment]
100% sure, the audio from DBM was a clear tell.
