### ISSUE TITLE
Lua error on Rashok, the Elder

### ISSUE THREAD

**Issue by brittyazel** [DeadlyBossMods/DBM-Retail#895]
On Normal Rashok, the Elder I received this error twice during the little circle soaks. It happened both times the little circles came out.

2x DBM-Core/DBM-Core.lua:2626: bad argument #2 to 'strsplit' (string expected, got boolean)
[string "=[C]"]: in function `strsplit'
[string "@DBM-Core/DBM-Core.lua"]:2626: in function `IsNonPlayableGUID'
[string "@DBM-Core/DBM-Core.lua"]:10093: in function <DBM-Core/DBM-Core.lua:9942>
[string "=(tail call)"]: ?
[string "@DBM-Aberrus/Rashok.lua"]:190: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:976: in function <DBM-Core/DBM-Core.lua:963>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:976: in function <DBM-Core/DBM-Core.lua:963>

Locals:
Skipped (In Encounter)

**Comment by MysticalOS** [comment]
That's fixed in alpha, I'll be doing a new release to address that soon. Thanks for report
