### ISSUE TITLE
Resto Shaman sometimes appearing as a Resto Druid

### ISSUE THREAD

**Issue by brittyazel** [DeadlyBossMods/DBM-Retail#896]
In Retail using version 10.1.8, I have hit an issue where one of my fellow healers (a Resto Shaman) is appearing sometimes as a Resto Druid. It's not always, and clearing all data will usually fix it until the point that it triggers again. I have not noticed any sort of pattern to what triggers this issue.

As you can see in the below screenshots, "Butch" is a Resto Shaman, but he is showing as a Resto Druid. (The upper screenshot is bugged, the bottom screenshot is correct.)

![Screenshot 2023-05-17 202126](https://github.com/DeadlyBossMods/DBM-Retail/assets/3747347/ec06e073-51cf-49f2-b3d1-f10c1d18a81a)
![Screenshot 2023-05-17 202151](https://github.com/DeadlyBossMods/DBM-Retail/assets/3747347/db76f51d-a8df-49dd-9a38-4780b9a9185e)

**Comment by MysticalOS** [comment]
This has nothing to do with DBM. I can't tell what damage meter that is but you'll want to ask them about it.

**Comment by brittyazel** [comment]
Oh crap, I'm so sorry. I thought I was in the Details repo. Sorry too many tabs open.
