### ISSUE TITLE
Entangling Countdown Alerts

### ISSUE THREAD

**Issue by Jaeger9671** [DeadlyBossMods/DBM-Retail#897]
For the love of God please shut these off or tell me how to.  I apologize for opening a Github issue since it isn't an issue with functionality but I couldn't find anywhere to comment.  Hearing a three second countdown every 10 seconds or so is driving me insane.

**Comment by MysticalOS** [comment]
it's every 30 seconds, but just go into affixes mod an disable the countdown for that spell.

**Comment by MysticalOS** [comment]
The following changes are in next update.

Countdown now starts at 3, instead of 4.
Countdown will no longer play when not in combat. Timer looping out of combat is intended but the countdown should now only play when vines are actually expected to spawn (in combat)
