### ISSUE TITLE
dbm ERRORS in chat

### ISSUE THREAD

**Issue by N6REJ** [DeadlyBossMods/DBM-Retail#900]
**Describe the bug**
errors randomly.  

**Do you have an error log of what happened?**

**To Reproduce**
I think its when doing instances.

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of DeadlyBossMods are you using?**
![image](https://github.com/DeadlyBossMods/DBM-Retail/assets/1850089/3d812bc2-21e9-4689-a34a-5b22a5b5858d)

**Was it working in a previous version? If yes, which was the last good one?**
yes, but idk which version it worked in.

**Additional context**

**Comment by N6REJ** [comment]
![WoWScrnShot_052623_184912](https://github.com/DeadlyBossMods/DBM-Retail/assets/1850089/e3874b94-13b1-47cb-8e87-537d7f7d37a8)

**Comment by MysticalOS** [comment]
delete the offending weak aura that it's calling out

**Comment by N6REJ** [comment]
which one might that be?

**Comment by N6REJ** [comment]
there is no "bostmus" wa

**Comment by MysticalOS** [comment]
says "bosmutus - zu" then name is cut off. it's a bad weak aura in your wa's somewhere

**Comment by N6REJ** [comment]
https://wago.io/search/bostmus

**Comment by N6REJ** [comment]
weird

**Comment by N6REJ** [comment]
OK, FOUND IT.. 
![image](https://github.com/DeadlyBossMods/DBM-Retail/assets/1850089/5eb921ad-4f5b-4517-9685-33d67d30d2d8)

**Comment by MysticalOS** [comment]
Gonna guess it was https://wago.io/AnrlsJf97 or something like it.
an obsolete version of timeline yes.
only version of timeline that's supported and working is
https://wago.io/RaidAbilityTimeline
if you still want to use that anyways
