### ISSUE TITLE
 Stage transition of  ATSC THE FORGOTTEN EXPERIMENTS.

### ISSUE THREAD

**Issue by GnomeTW** [DeadlyBossMods/DBM-Retail#902]
**Describe the bug**
Is it possible to add stage transition triggers to the encounter ATSC THE FORGOTTEN EXPERIMENTS? In MRT NOTE, we often use notations like p2, p3 to trigger WeakAuras. However, this requires DBM to be able to trigger stage changes. According to the World of Warcraft Combat Log (WCL), THE FORGOTTEN EXPERIMENTS does indeed have three distinct stages.

**Do you have an error log of what happened?**
no.

**Which version of DeadlyBossMods are you using?**
10.1.10

**Additional context**
zhTW

**Comment by MysticalOS** [comment]
I usually apply stages to match journal. the journal doesn't stage the fight so that's why DBM doesn't.

Curious, what specific trigger would benefit from stages on this fight?

**Comment by GnomeTW** [comment]
> I usually apply stages to match journal. the journal doesn't stage the fight so that's why DBM doesn't.
> 
> Curious, what specific trigger would benefit from stages on this fight?

Although I'm not sure if I can explain it well, I'll try to clarify the issue. Thank you for being willing to understand.

Let me use the SPELL as an example, such as "Deep Breath (4)". In MRT notes, I can use two different formats to trigger WA, for example, the {time:xx:xx} format or the {time:xx:xx,p3} format. However, the DPS strength affects the achievement of the condition "Thadrion 50% HP (p3)" at different times, which leads to incorrect countdowns for "Deep Breath (4)" using the {time:xx:xx} format. This is because "Deep Breath (4)" doesn't start counting down at the beginning of the fight, but rather when the condition "Thadrion 50% HP" is met. Therefore, for different teams, "Deep Breath (4)" can occur with a difference of up to 1 minute between {time:05:06} and {time:06:09}. However, using {time:xx:xx,p3} can get closer to the timeline.

If I want to use the {time:xx:xx,p3} format in MRT notes to trigger WA, I need to be able to receive transition notifications from DBM.

I'm not sure if my understanding is correct, so if I'm mistaken, I would appreciate it if you could correct my understanding.

**Comment by MysticalOS** [comment]
Added in https://github.com/DeadlyBossMods/DBM-Retail/commit/dc2702c1e48e79203178284e756a691d276f45bf
