### ISSUE TITLE
Private Aura alert is firing independent of any boss mod being loaded

### ISSUE THREAD

**Issue by TheCheat54** [DeadlyBossMods/DBM-Retail#903]
**Describe the bug**

The private aura alert which seems to be buried inside the DBM core module is firing inside Aberrus during the Echo of Neltharion fight even though I have the Aberrus module disabled. I still use DBM for dungeon mods but do not use the raid modules, and this disruption is unwelcome. (The sound effect is also not configurable anywhere in the core options, but that is more of a feature request than part of this bug.)

**Do you have an error log of what happened?**

No error is thrown.

**To Reproduce**

1. Install the mod and disable the Aberrus module before logging in.
2. Fight Echo of Neltharion and wait to be targeted by Volcanic Heartbeat or Rushing Darkness.
3. Hear that a sound alert for these abilities plays (it's an airhorn in my client).

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

My test actually was done in reverse, as I originally reported this as a bug to BigWigs. They recommended I turn off the DBM core, so I did this and re-tested; the airhorn sound alert no longer played when targeted by either of Echo's abilities.

**Which version of DeadlyBossMods are you using?**

As of my test, 10.1.12 alpha (2023/05/30 08:14:38)

**Was it working in a previous version? If yes, which was the last good one?**

This issue was not present the first week of the raid, but has been present on every one of my subsequent kills starting in the second reset.

**Comment by MysticalOS** [comment]
that's very odd, oncombatstart and registering the aura literally won't happen if module is disabled. so I don't know. it doesn't register the auras willy nilly, it requires the module to fire combat start, and for the initial oncombatstart stuff to run. and nothing else from mod started? cause if oncombat start ran it shoulda also started timers and everything else.

**Comment by TheCheat54** [comment]
Not sure on that. With the module disabled the Volcanic Heartbeat spell ID shouldn't even be referenced for example since I only found it in the Aberrus lua file. I've only ever loaded the Aberrus module once and it was during the first week because I forgot to disable it; had it disabled ever since.

**Comment by MysticalOS** [comment]
I'll look at it but it's odd, it doesn't register the sound until boss is engaged with module loaded, and it immediately unregisters on combat end. so it's only ever registering dbm media if module is active during that pull. and yes not configuring sound is on todo list, for most part most actual DBM raid module users will have the voice pack enabled too.

Glad you're using DBM for dungeons though, I guess for awesome plater feature?

**Comment by TheCheat54** [comment]
That and the fact all my alerts were already configured how I wanted so I didn't want to rock the boat in that department.

**Comment by Mitalie** [comment]
Perhaps some other addon or weakaura is registering private aura sounds using the DBM airhorn via LibSharedMedia? With DBM-Core disabled, the airhorn sound isn't registered with LSM, so the other addon either gives up or passes invalid sound file to Blizzard's `C_UnitAuras.AddPrivateAuraAppliedSound`.

**Comment by MysticalOS** [comment]
well DBM does use airhorn for registering so something weird going on, don't know. i suspect module wasn't fully disabled cause it fired oncombatstart somehow

**Comment by TheCheat54** [comment]
This is how it's been since I disabled it a few weeks ago. I did this at the login screen to ensure it took effect for all characters.

![image](https://github.com/DeadlyBossMods/DBM-Retail/assets/60072292/e93f0a6b-e1d2-404d-bd2d-c337bd13666d)
