### ISSUE TITLE
Nethalrions lair spiked tongue warning missing

### ISSUE THREAD

**Issue by N6REJ** [DeadlyBossMods/DBM-Retail#906]
**Describe the bug**
When spiked tongue is about to occur an announcement should be made.

**Do you have an error log of what happened?**

**To Reproduce**

1. Go to neltharions lair to the wyrm boss
2. wait for "spiked tongue" attack

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
no

**Which version of DeadlyBossMods are you using?**
10.1.12

**Was it working in a previous version? If yes, which was the last good one?**
unknown 
**Additional context**

**Comment by MysticalOS** [comment]
I'm gonna assume you're not the tank. the tank gets a massive run away alert.

**Comment by N6REJ** [comment]
I was the tank.  And didn't get any alert

**Comment by MysticalOS** [comment]
Either mod was disabled or not installed. the warning is loud and clear. I suspect you're missing DBM Dungeons addon download (Ie you only have core and raids)
