### ISSUE TITLE
Pull timer voice count down.

### ISSUE THREAD

**Issue by derpaherk** [DeadlyBossMods/DBM-Retail#907]
While in M+ the pull count down time will start to verbally start to count down at 5 seconds to pull, which is what I want.

It used to do this in Raids but now it doesn't.  Where is the setting to change this?  I always used it as a cue to tell me when to pay attention.  I'm sure I made a chance somewhere. Mainly asking where you can  change this at. Or is this not configurable? I'd rather not reset to defaults as I'd have to remember all of my settings, but if that is how to fix it ok.

No logs... as its not causing any bug.

Be in a raid. Have raid leader do a /pull #

**Which version of DeadlyBossMods are you using?**
Using current version
**Was it working in a previous version? If yes, which was the last good one?**
It was.. but I dont know when it stopped.

**Comment by QartemisT** [comment]
Apologies for the massive delay.

If you check under your spoken alerts section, there should be a setting for "countdown voice" :)

**Comment by fistdlanthus** [comment]
I am also having this problem with the most recent version.  And i have checked the above

**Comment by fistdlanthus** [comment]
i reinstalled the august 8 DBM-10.1.21 version and it works in there
