### ISSUE TITLE
All bars have '~' prefix

### ISSUE THREAD

**Issue by simonbob2** [DeadlyBossMods/DBM-Retail#914]
**Describe the bug**
Not sure if this a bug or not, but I wasn't able to find any settings that could possibly disable this. 

**Do you have an error log of what happened?**
No

**Screenshots**
![image](https://github.com/DeadlyBossMods/DBM-Retail/assets/139992802/92865cd5-d9a5-4f7c-ab66-5267c66b81cb)

**Which version of DeadlyBossMods are you using?**
10.1.17

**Was it working in a previous version? If yes, which was the last good one?**
No, it's been like this since I got it

**Additional context**
It persists only in content, but it's not visible on test bars.

**Comment by MysticalOS** [comment]
That's not a bug. it signifies it's a CD timer and not an exact one. Ideally the ~ would be in front of number instead of text but that hasn't been implemented yet

**Comment by simonbob2** [comment]
How would I move or disable this?

**Comment by MysticalOS** [comment]
you can't.

**Comment by simonbob2** [comment]
Ok thank you.

**Comment by MysticalOS** [comment]
Just to add to this, update that is going out today has moved the ~ from the timer text to the timer itself, matching behavior of other mods going forward.
