### ISSUE TITLE
DBM-Archaeology 'Playsound' error

### ISSUE THREAD

**Issue by CarolAsh15** [DeadlyBossMods/DBM-Retail#919]
Lua Error occurs when looting a keystone during Archaeology in Eastern Kingdoms 

Message: Interface/AddOns/DBM-Archaeology/Archaeology.lua:83: attempt to call method 'PlaySound' (a nil value)
Time: Sun Aug  6 12:32:50 2023
Count: 1
Stack: Interface/AddOns/DBM-Archaeology/Archaeology.lua:83: attempt to call method 'PlaySound' (a nil value)
[string "@Interface/AddOns/DBM-Archaeology/Archaeology.lua"]:83: in function <Interface/AddOns/DBM-Archaeology/Archaeology.lua:70>

Locals: self = DBM_Archaeology {
 0 = <userdata>
}
event = "CHAT_MSG_LOOT"
player = "You"
itemID = "63128"
(*temporary) = nil
(*temporary) = <table> {
 SelectGossip = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2847
 GetUnitIdFromCID = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2772
 CHAT_MSG_ADDON_LOGGED = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:4647
 StopLogging = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:5904
 FindScenarioIDs = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6903
 GetNumGuildPlayersInZone = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2513
 VibrateController = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6869
 FindDungeonMapIDs = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6895
 GetUnitIdFromGUID = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2594
 CopyProfile = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:1979
 CHAT_MSG_MONSTER_EMOTE = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:5004
 CHAT_MSG_WHISPER = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6630
 SendPVPTimers = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6428
 DeleteProfile = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:1996
 DungeonMusic = <table> {
 }
 ShowUpdateReminder = <function> defined @Interface/AddOns/DBM-Core/modules/UpdateReminder.lua:76
 GetRaidRoster = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2549
 PLAYER_REGEN_DISABLED = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:4769
 FireEvent = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:1887
 CreateModLocalization = <function> defined @Interface/AddOns/DBM-Core/modules/objects/Localization.lua:89
 SCENARIO_COMPLETED = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:3520
 IsEnabled = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6716
 GetMyPlayerInfo = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2617
 ADDON_LOADED = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:1569
 IconNumToTexture = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6884
 BattleMusic = <table> {
 }
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2484
 AddDefeatSound = <function> defined @Interface/AddOns/DBM-Core/modules/Sounds.lua:117
 SortByMeleeRoster = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:7743
 GetBossUnitId = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2754
 SendCombatInfo = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6450
 AddDefaultOptions = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2870
 UPDATE_MOUSEOVER_UNIT = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:3850
 InfoFrame = <table> {
 }
 registeredUnitEvents = <table> {
 }
 FilterRaidBossEmote = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:1404
 RequestTimers = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6325
 VoiceVersions = <table> {
 }
 Voices = <table> {
 }
 AddOns = <table> {
 }
 Options = <table> {
 }
 GetModLocalization = <function> defined @Interface/AddOns/DBM-Core/modules/objects/Localization.lua:106
 UPDATE_BATTLEFIELD_STATUS = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:3498
 GetModByName = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:7049
 CheckNearby = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2796
 GetMusic = <function> defined @Interface/AddOns/DBM-Core/modules/Sou

DBM Archaeology version 10.1.5 both Alpha and Release versions produce error.

**Comment by QartemisT** [comment]
DBM-Archaeology version "r55" is being pushed now, which has fixes for this :)
