### ISSUE TITLE
[Not Bug] MRT pull timer not compatible with newest DBM

### ISSUE THREAD

**Issue by Nekrokit** [DeadlyBossMods/DBM-Retail#922]
In version 10.1.21 and before "/rt pull/afk x" (as command from MRT) shows DBM bar with time left.
From 10.1.23 it stopped working, with no lua errors (console scriptErrors 1).

It doesn't matter if it's raid/party, it can be reproduced solo.

**Comment by QartemisT** [comment]
Please file the issue with MRT.

We officially stopped supporting old comms channels, as we depreacted them 6 months ago. They've had more than enough time to update.

**Comment by MysticalOS** [comment]
Posting here for reference and reopening ticket for now:
https://github.com/DeadlyBossMods/DBM-Retail/wiki/%5BDeveloper%5D-Notice-of-old-addon-comm-deprecation

**Comment by QartemisT** [comment]
This was fixed as of;
<https://www.curseforge.com/wow/addons/method-raid-tools/files/4722112>, a month and half ago :D
