### ISSUE TITLE
Constant error as soon as you start "Forgotten Experiments" Heroic

### ISSUE THREAD

**Issue by greenstones** [DeadlyBossMods/DBM-Retail#924]
**Describe the bug**
Bug starts happening as soon as you start Heroic Forgotten Experiments as a tank;

Bugsack capture:
502x DBM-Core/DBM-InfoFrame.lua:291: attempt to compare number with string
[string "@DBM-Core/DBM-InfoFrame.lua"]:291: in function <DBM-Core/DBM-InfoFrame.lua:290>
[string "=[C]"]: ?
[string "@DBM-Core/DBM-InfoFrame.lua"]:318: in function <DBM-Core/DBM-InfoFrame.lua:302>
[string "@DBM-Core/DBM-InfoFrame.lua"]:826: in function `?'
[string "@DBM-Core/DBM-InfoFrame.lua"]:951: in function <DBM-Core/DBM-InfoFrame.lua:949>
[string "@DBM-Core/DBM-InfoFrame.lua"]:1165: in function <DBM-Core/DBM-InfoFrame.lua:1164>

Locals:
Skipped (In Encounter)

Current Available Version of DBM: 10.1.23
(Downloaded from curseforge.)

Tried to resolve with a /reload however error continued to occur.

**Comment by MysticalOS** [comment]
This is fixed in alpha few days ago. I just didn't redo a new release with fix just yet.
