### ISSUE TITLE
Symmetry broken on Bar Options Offset

### ISSUE THREAD

**Issue by Anothersignup** [DeadlyBossMods/DBM-Retail#934]
**Is your feature request related to a problem? Please describe.**
Bar (x) offsets can't be set back to 0.

**Describe the solution you'd like**
Be able to type in my number, instead of using sliders.

**Describe alternatives you've considered**

**Additional context**

**Comment by QartemisT** [comment]
I've double checked the code, and verified in-game. It allows you to go from -50 to +50, at intervals of 1. If your UI is skipping this, it's likely a 3rd party addon modifying sliders or something.

If you're still struggling, you can always run `/run DBT.Options.BarXOffset = 0` for the small bar, and `/run DBT.Options.HugeBarXOffset = 0` for the large bar.

**Comment by QartemisT** [comment]
You will need to `/reload` after for it to take effect.

**Comment by MysticalOS** [comment]
And if the skin that's altering it is still active, it will just keep overriding it.
