### ISSUE TITLE
'DBM-Core' tried to call the protected function 'CancelScene()' during Sanctum of Domination Mythic

### ISSUE THREAD

**Issue by brittyazel** [DeadlyBossMods/DBM-Retail#937]
When running Sanctum of Domination Mythic I received this error:

DBM is fully up-to-date as of the time of reporting this bug.

```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'DBM-Core' tried to call the protected function 'CancelScene()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `CancelScene'
[string "@FrameXML/CinematicFrame.lua"]:193: in function `CinematicFrame_CancelCinematic'
[string "@DBM-Core/DBM-Core.lua"]:6910: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1055: in function <DBM-Core/DBM-Core.lua:1042>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

```

**Comment by brittyazel** [comment]
The same showed up on the Sylvanas fight.

**Comment by MysticalOS** [comment]
Yeah, blizzard decided randomly this week to make it a protected function. I just killed off DBms feature to auto cancel but scenes during fights. users are gonna have to manually skip them from now on.

**Comment by TheCheat54** [comment]
Even though this error is being thrown, the cinematic skips were still successful for me. Is simply the error's presence enough for you to want to remove the functionality?

**Comment by MysticalOS** [comment]
The error actually encourages users to disable DBM. An uninformed user will consider this a problem with DBM and continue opening issues with us, or worse, uninstall mod thinking it's causing problems with their game. So until blizzard fixes how much they broke with https://github.com/Stanzilla/WoWUIBugs/issues/483 , the feature is just retired.

**Comment by hayatofujii** [comment]
Was `CancelScene()` actually protected or it's a random Blizzard victim?

**Comment by Taizunz** [comment]
> Was `CancelScene()` actually protected or is it a random Blizzard victim?

It was not protected, just a bug as mentioned in the message before yours. Some addons are disabling/removing their Cinematic/Cutscene skip functionality temporarily, to prevent errors and additional user reports.
