### ISSUE TITLE
HeadlessHorseman - attempt to perform arithmetic on field 'ignitingCount' (a nil value)

### ISSUE THREAD

**Issue by Malivil** [DeadlyBossMods/DBM-Retail#944]
**Describe the bug**
2023 Headless Horseman encounter. 3-5 times during the fight this error will occur

**Do you have an error log of what happened?**
Message: ...AddOns/DBM-WorldEvents/Holidays/HeadlessHorseman.lua:93: attempt to perform arithmetic on field 'ignitingCount' (a nil value)
Time: Thu Oct 19 09:46:19 2023
Count: 2
Stack: ...AddOns/DBM-WorldEvents/Holidays/HeadlessHorseman.lua:93: attempt to perform arithmetic on field 'ignitingCount' (a nil value)
[string "@Interface/AddOns/DBM-WorldEvents/Holidays/HeadlessHorseman.lua"]:93: in function `handler'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:1061: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:1048>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:1061: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:1048>

Locals: self = <table> {
 stats = <table> {
 }
 SyncThreshold = 8
 numBoss = 1
 ignoreBestkill = false
 modId = "DBM-WorldEvents"
 engagedDiffText = "Event - "
 revision = 20231019035830
 DefaultOptions = <table> {
 }
 iconRestore = <table> {
 }
 OnCombatStart = <function> defined @Interface/AddOns/DBM-WorldEvents/Holidays/HeadlessHorseman.lua:54
 engagedDiffIndex = 19
 SPELL_DAMAGE = <function> defined @Interface/AddOns/DBM-WorldEvents/Holidays/HeadlessHorseman.lua:108
 localization = <table> {
 }
 announces = <table> {
 }
 subTab = 1
 SPELL_MISSED = <function> defined @Interface/AddOns/DBM-WorldEvents/Holidays/HeadlessHorseman.lua:108
 categorySort = <table> {
 }
 groupSpells = <table> {
 }
 GOSSIP_SHOW = <function> defined @Interface/AddOns/DBM-WorldEvents/Holidays/HeadlessHorseman.lua:116
 inCombat = true
 engagedDiff = "event5"
 zones = <table> {
 }
 combatInfo = <table> {
 }
 Options = <table> {
 }
 inCombatOnlyEventsRegistered = 1
 addon = <table> {
 }
 SPELL_CAST_START = <function> defined @Interface/AddOns/DBM-WorldEvents/Holidays/HeadlessHorseman.lua:65
 specwarns = <table> {
 }
 timers = <table> {
 }
 encounterId = 2725
 groupOptions = <table> {
 }
 SPELL_AURA_APPLIED = <function> defined @Interface/AddOns/DBM-WorldEvents/Holidays/HeadlessHorseman.lua:98
 optionCategories = <table> {
 }
 creatureId = 207438
 id = "d285"
 vb = <table> {
 }
 inCombatOnlyEvents = <table> {
 }
}
args = <table> {
 sourceName = "Headless Horseman"
 destFlags = -2147483648
 spellId = 415047
 spellName = "Vine March"
 event = "SPELL_CAST_START"
 sourceRaidFlags = 0
 destRaidFlags = -2147483648
 destGUID = ""
 timestamp = 1697723179.208000
 sourceFlags = 68168
 sourceGUID = "Vehicle-0-4254-1004-4666-207438-00003132D9"
}
spellId = 415047
timer = 20.600000
(*temporary) = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:10218
(*temporary) = <table> {
 spellId = 415047
 icon = 415052
 type = "cdcount"
 simpType = "cd"
 id = "Timer415047cdcount"
 option = "Timer415047cdcount"
 startedTimers = <table> {
 }
 colorType = 1
 name = "Vine March"
 mod = <table> {
 }
 timer = 41.400000
}
(*temporary) = 20.600000
(*temporary) = nil
(*temporary) = 415047
(*temporary) = 1
(*temporary) = "attempt to perform arithmetic on field 'ignitingCount' (a nil value)"
specWarnInsidiousCackle = <table> {
 voiceOptionId = "Voice415262"
 hasVoice = 2
 spellId = 415262
 icon = 136185
 option = "SpecWarn415262moveaway"
 text = "Insidious Cackle - move away from others"
 flash = 1
 combinedcount = 0
 mod = <table> {
 }
 announceType = "moveaway"
 type = "moveaway"
 combinedtext = <table> {
 }
 sound = true
 spellName = "Insidious Cackle"
}
allTimers = <table> {
 414844 = <table> {
 }
 415262 = <table> {
 }
 415047 = <table> {
 }
 423626 = <table> {
 }
}
timerInsidiousCackleCD = <table> {
 spellId = 415262
 icon = 136185
 type = "cdcount"
 simpType = "cd"
 id = "Timer415262cdcount"
 option = "Timer415262cdcount"
 startedTimers = <table> {
 }
 colorType = 2
 name = "Insidious Cackle"
 mod = <table> {
 }
 timer = 41.400000
}
specWarnPumpkinBreath = <table> {
 voiceOptionId = "Voice414844"
 hasVoice = 2
 spellId = 414844
 icon = 524795
 option = "SpecWarn414844dodgecount"
 text = "Pumpkin Breath (%s) - dodge attack"
 flash = 2
 combinedcount = 0
 mod = <table> {
 }
 announceType = "dodgecount"
 type = "dodge

**To Reproduce**
1. Join Headless Horseman event in LFG
2. Start the event
3. 3-5 times during the event, this error will happen

**Screenshots**
![image](https://github.com/DeadlyBossMods/DBM-Retail/assets/1238511/f23fd17d-f0a7-4b4b-a3ff-fc039244473c)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
10.1.30

**Was it working in a previous version? If yes, which was the last good one?**
Error didn't occur previously but I think this version is the first with the updated event

**Additional context**

**Comment by QartemisT** [comment]
Hiya. This is fixed in the latest alpha :)
