### ISSUE TITLE
Vault of the Incarnate: No player markers for Static Charge

### ISSUE THREAD

**Issue by Aurilia-Gilneas** [DeadlyBossMods/DBM-Retail#947]
**Describe the bug**

During the Raszageth encounter in Vault of the Incarnates, target markers did not appear over players' heads to assist with placing the Static Fields.  (Players running DBM were still /saying their markers)

**Do you have an error log of what happened?**

4x DBM-Core/DBM-InfoFrame.lua:492: bad argument #1 to 'UnitExists' (Usage: local result = UnitExists([unit]))
[string "=[C]"]: ?
[string "@DBM-Core/DBM-InfoFrame.lua"]:492: in function `?'
[string "@DBM-Core/DBM-InfoFrame.lua"]:1153: in function `Show'
[string "@DBM-Raids-Dragonflight/VaultoftheIncarnates/RaszageththeStormEater.lua"]:458: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1064: in function <DBM-Core/DBM-Core.lua:1051>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1064: in function <DBM-Core/DBM-Core.lua:1051>

Locals:
Skipped (In Encounter)

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
no

**Which version of DeadlyBossMods are you using?**
Group was a mix of 10.2.1 (including raid leader and one assist) and a tank with assist running 10.2.2 Alpha

**Was it working in a previous version? If yes, which was the last good one?**
Was working last week prior to WoW 10.2 Patch and related DBM update(s)

**Additional context**

**Comment by MysticalOS** [comment]
this might be related to combat log bug where all names in combatlog are unabiguated. I feel like by the time i push a fix for it, blizzard will have already fixed it

**Comment by MysticalOS** [comment]
BTW i don't think that error is actually cause of your issue, any other errors?

I'm stumped as to what's causing your issue. combat log probably causing icon marking issue though.

**Comment by MysticalOS** [comment]
Icon issue should be fixed in new core update so closing this
