### ISSUE TITLE
DBM Lua Error on loading in to dungeon

### ISSUE THREAD

**Issue by Rittler281** [DeadlyBossMods/DBM-Retail#948]
**Do you have an error log of what happened?**

Message: ...AddOns/DBM-Party-WoD/EverBloom/AncientProtectors.lua:61: attempt to call method 'NewTargetNofilterAnnounce' (a nil value)
Time: Fri Nov 10 16:50:57 2023
Count: 1
Stack: ...AddOns/DBM-Party-WoD/EverBloom/AncientProtectors.lua:61: attempt to call method 'NewTargetNofilterAnnounce' (a nil value)
[string "=[C]"]: in function `NewTargetNofilterAnnounce'
[string "@Interface/AddOns/DBM-Party-WoD/EverBloom/AncientProtectors.lua"]:61: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:3815: in function `LoadMod'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:3760: in function `LoadModsOnDemand'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:3698: in function `func'
[string "@Interface/AddOns/DBM-Core/modules/Scheduler.lua"]:171: in function <Interface/AddOns/DBM-Core/modules/Scheduler.lua:162>

Locals: (*temporary) = <function> defined =[C]:-1

**To Reproduce**

Zoning in to dungeons (Timewalking WoD) / manually clicking on load addon under the "Dungeons (WoD)". Will assume this happens when Everbloom goes live when s3 starts.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of DeadlyBossMods are you using?**

10.2.2

**Comment by MysticalOS** [comment]
That's already fixed in alpha, there will be a new release late monday or early tuesday

**Comment by Rittler281** [comment]
> That's already fixed in alpha, there will be a new release late monday or early tuesday

Awesome to hear, thank you!
