### ISSUE TITLE
Errors occurring during boss fights.

### ISSUE THREAD

**Issue by Ookami313** [DeadlyBossMods/DBM-Retail#949]
**Describe the bug**
Running new Amirdrassill raid on normal and receieved the following errors.

**Do you have an error log of what happened?**
2x ...ddOns/DBM-Raids-Dragonflight/Amirdrassil/Larodar.lua:504: attempt to call method 'Yell' (a nil value)
[string "@DBM-Raids-Dragonflight/Amirdrassil/Larodar.lua"]:504: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1064: in function <DBM-Core/DBM-Core.lua:1051>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1064: in function <DBM-Core/DBM-Core.lua:1051>

Locals:
Skipped (In Encounter)

6x ...M-Raids-Dragonflight/Amirdrassil/CouncilofDreams.lua:139: attempt to call method 'Mythic' (a nil value)
[string "@DBM-Raids-Dragonflight/Amirdrassil/CouncilofDreams.lua"]:139: in function <...M-Raids-Dragonflight/Amirdrassil/CouncilofDreams.lua:123>
[string "@DBM-Raids-Dragonflight/Amirdrassil/CouncilofDreams.lua"]:293: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1064: in function <DBM-Core/DBM-Core.lua:1051>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1064: in function <DBM-Core/DBM-Core.lua:1051>

Locals:
Skipped (In Encounter)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, errors occurred while in combat.

**Which version of DeadlyBossMods are you using?**
10.2.3

**Was it working in a previous version? If yes, which was the last good one?**
Unknown. Updated to newest version before entering raid.

**Additional context**

**Comment by MysticalOS** [comment]
Fixed in latest alpha
