### ISSUE TITLE
Aurostor world boss marked as wipe due to boss becoming friendly rather than dying

### ISSUE THREAD

**Issue by InvisiBilldotnet** [DeadlyBossMods/DBM-Retail#960]
**Describe the bug**
Completed "kills" of Aurostor in Emerald Dream are seen by DBM as a wipe rather than successful, since Aurostor isn't actually taken to 0% and killed, but instead becomes friendly at low health.

**To Reproduce**
1. Fight Aurostor to completion
2. Get DBM "wipe" message

**Screenshots**
![image](https://github.com/DeadlyBossMods/DBM-Retail/assets/21955683/5f9482ce-14cd-42f4-8b41-4d45dd9c0ae4)

**Which version of DeadlyBossMods are you using?**
10.2.8

**Was it working in a previous version? If yes, which was the last good one?**
No, as far as I know

**Comment by MysticalOS** [comment]
it's fixed in alpha already, along with actually supporting bosses abilities
