### ISSUE TITLE
DBM Error (Lady Sarevess) SOD

### ISSUE THREAD

**Issue by seskobrodo** [DeadlyBossMods/DBM-Retail#974]
**Describe the bug**

During Lady Sarevess each run, I get a LUA error Pop-up mid fight, and its starting to get a bit annoying :D.

**Do you have an error log of what happened?**

Only a screenshot from the VOD. 

**To Reproduce**

Fight Lady Sarevess, and then it happens at roughly 60% hp. 

**Screenshots**

![Skjermbilde 2023-12-29 170740](https://github.com/DeadlyBossMods/DBM-Retail/assets/75147266/065f2fc0-afb6-4907-8dbf-fe1a5cddf575)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No.

**Which version of DeadlyBossMods are you using?**

The newest during the incidents. 

**Was it working in a previous version? If yes, which was the last good one?**

No.

**Additional context**

Blank.

**Comment by QartemisT** [comment]
This has already been fixed here <https://github.com/DeadlyBossMods/DBM-BCVanilla/commit/19ae1152cdb388a978681475a605c7c9b81437c3>

Please make sure you are up-to-date.

**Comment by seskobrodo** [comment]
> This has already been fixed here [DeadlyBossMods/DBM-BCVanilla@19ae115](https://github.com/DeadlyBossMods/DBM-BCVanilla/commit/19ae1152cdb388a978681475a605c7c9b81437c3)
> 
> Please make sure you are up-to-date.

![Skjermbilde 2023-12-29 183752](https://github.com/DeadlyBossMods/DBM-Retail/assets/75147266/75e8edae-51fb-41d2-a271-d77325f35c83)

Excuse me? 😂

**Comment by seskobrodo** [comment]
> This has already been fixed here [DeadlyBossMods/DBM-BCVanilla@19ae115](https://github.com/DeadlyBossMods/DBM-BCVanilla/commit/19ae1152cdb388a978681475a605c7c9b81437c3)
> 
> Please make sure you are up-to-date.

Please dont close issues that hasn't yet been fixed...

**Comment by QartemisT** [comment]
It appears to be in the latest alpha version resolved. Going to blame @MysticalOS for not having done a new release sooner :P

**Comment by seskobrodo** [comment]
> It appears to be in the latest alpha version resolved. Going to blame @MysticalOS for not having done a new release sooner :P
Its ok, I just made a new post! :).
