### ISSUE TITLE
DBM Error (Lady Sarevess) SOD Attempt 2

### ISSUE THREAD

**Issue by seskobrodo** [DeadlyBossMods/DBM-Retail#975]
Note: Had to re-open the issue because a member closed is as fixed...

Describe the bug

During Lady Sarevess each run, I get a LUA error Pop-up mid fight, and its starting to get a bit annoying :D.

Do you have an error log of what happened?

Only a screenshot from the VOD.

To Reproduce

Fight Lady Sarevess, and then it happens at roughly 60% hp.

Screenshots

![Skjermbilde 2023-12-29 170740](https://github.com/DeadlyBossMods/DBM-Retail/assets/75147266/a3bc78cd-782d-4f87-9805-8133037decee)

Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?

No.

Which version of DeadlyBossMods are you using?

The newest during the incidents.

Was it working in a previous version? If yes, which was the last good one?

No.

Additional context

Blank.

**Comment by Molkree** [comment]
Should be fixed in https://github.com/DeadlyBossMods/DBM-Classic/releases/tag/1.15.6

**Comment by MysticalOS** [comment]
It was closed because it was fixed, 3 and a half weeks ago, the tag was a bit late (cause I forgot to do one) but that was done 3 days ago
