### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Imna1975** [DeadlyBossMods/DBM-Retail#986]
1x DBM-Core/DBM-Core.lua:7209: attempt to concatenate local 'currentMapID' (a nil value)
[string "@DBM-Core/DBM-Core.lua"]:7209: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1140: in function <DBM-Core/DBM-Core.lua:1127>

Locals:
self = <table> {
 SelectGossip = <function> defined @DBM-Core/DBM-Core.lua:2972
 GetUnitIdFromCID = <function> defined @DBM-Core/DBM-Core.lua:2862
 CHAT_MSG_ADDON_LOGGED = <function> defined @DBM-Core/DBM-Core.lua:4796
 IsRetail = <function> defined @DBM-Core/DBM-Core.lua:7558
 StopLogging = <function> defined @DBM-Core/DBM-Core.lua:6073
 FindScenarioIDs = <function> defined @DBM-Core/DBM-Core.lua:7135
 GetNumGuildPlayersInZone = <function> defined @DBM-Core/DBM-Core.lua:2600
 VibrateController = <function> defined @DBM-Core/DBM-Core.lua:7101
 FindDungeonMapIDs = <function> defined @DBM-Core/DBM-Core.lua:7127
 GetUnitIdFromGUID = <function> defined @DBM-Core/DBM-Core.lua:2684
 CopyProfile = <function> defined @DBM-Core/DBM-Core.lua:2066
 CHAT_MSG_MONSTER_EMOTE = <function> defined @DBM-Core/DBM-Core.lua:5151
 CHAT_MSG_WHISPER = <function> defined @DBM-Core/DBM-Core.lua:6862
 SendPVPTimers = <function> defined @DBM-Core/DBM-Core.lua:6657
 DeleteProfile = <function> defined @DBM-Core/DBM-Core.lua:2083
 DungeonMusic = <table> {
 }
 ShowUpdateReminder = <function> defined @DBM-Core/modules/UpdateReminder.lua:80
 GetRaidRoster = <function> defined @DBM-Core/DBM-Core.lua:2639
 PLAYER_REGEN_DISABLED = <function> defined @DBM-Core/DBM-Core.lua:4913
 FireEvent = <function> defined @DBM-Core/DBM-Core.lua:1974
 CreateModLocalization = <function> defined @DBM-Core/modules/objects/Localization.lua:99
 SCENARIO_COMPLETED = <function> defined @DBM-Core/DBM-Core.lua:3645
 IsEnabled = <function> defined @DBM-Core/DBM-Core.lua:6943
 GetMyPlayerInfo = <function> defined @DBM-Core/DBM-Core.lua:2707
 ADDON_LOADED = <function> defined @DBM-Core/DBM-Core.lua:1638
 IconNumToTexture = <function> defined @DBM-Core/DBM-Core.lua:7116
 ReceiveVariableInfo = <function> defined @DBM-Core/DBM-Core.lua:6607
 registeredUnitEvents = <table> {
 }
 BattleMusic = <table> {
 }
 VoiceVersions = <table> {
 }
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @DBM-Core/DBM-Core.lua:2571
 Voices = <table> {
 }
 AddDefeatSound = <function> defined @DBM-Core/modules/Sounds.lua:123
 AddOns = <table> {
 }
 SortByMeleeRoster = <function> defined @DBM-Core/DBM-Core.lua:8050
 Options = <table> {
 }
 GetBossUnitId = <function> defined @DBM-Core/DBM-Core.lua:2844
 GetModLocalization = <function> defined @DBM-Core/modules/objects/Localization.lua:116
 AddDefaultOptions = <function> defined @DBM-Core/DBM-Core.lua:2995
 UPDATE_MOUSEOVER_UNIT = <function> defined @DBM-Core/DBM-Core.lua:4005
 ZONE_CHANGED_NEW_AREA = <function> defined @DBM-Core/DBM-Core.lua:3850
 CINEMATIC_START = <function> defined @DBM-Core/DBM-Core.lua:7202
 FilterRaidBossEmote = <function> defined @DBM-Core/DBM-Core.lua:1473
 RequestTimers = <function> defined @DBM-Core/DBM-Core.lua:6554
 GetMusic = <function> defined @DBM-Core/modules/Sounds.lua:245
 Music = <table> {
 }
 SortByGroup = <function> defined @DBM-Core/DBM-Core.lua:7999
 GetBattleMusic = <function> defined @DBM-Core/modules/Sounds.lua:211
 RAID_BOSS_WHISPER = <function> defined @DBM-Core/DBM-Core.lua:5173
 UPDATE_BATTLEFIELD_STATUS = <function> defined @DBM-Core/DBM-Core.lua:3623
 GetDungeonMusic = <function> defined @DBM-Core/modules/Sounds.lua:163
 CheckNearby = <function> defined @DBM-Core/DBM-Core.lua:2887
 GetDefeatSounds = <function> defined @DBM-Core/modules/Sounds.lua:116
 CHAT_MSG_MON

**Comment by MysticalOS** [comment]
where were you when you triggered this?

**Comment by emmericp** [comment]
From the other bug:

To Reproduce
Working on the United Again storyline
Accepted The Last Conflict quest in the chain.
Entered the Azure Vault instance. (First occurrence of error)
Finished Quest and exited instance (second occurrence of error)
