### ISSUE TITLE
DBM-Core.lua:7209: attempt to concatenate local 'currentMapID' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [DeadlyBossMods/DBM-Retail#987]
**Describe the bug**
Updated to 10.2.20. Working on the Blue Dragon Flight United Gain story quest chain. As soon as I reached the later part of the chain where you enter the Azure Archives, upon accepting the quest and entering the instance the following error occurred. A second occurrence of the error happened again after finishing the quest and exiting the instance. Thanks.

**Do you have an error log of what happened?**
2x DBM-Core/DBM-Core.lua:7209: attempt to concatenate local 'currentMapID' (a nil value)
[string "@DBM-Core/DBM-Core.lua"]:7209: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1140: in function <DBM-Core/DBM-Core.lua:1127>

Locals:
self = <table> {
 SelectGossip = <function> defined @DBM-Core/DBM-Core.lua:2972
 GetUnitIdFromCID = <function> defined @DBM-Core/DBM-Core.lua:2862
 CHAT_MSG_ADDON_LOGGED = <function> defined @DBM-Core/DBM-Core.lua:4796
 IsRetail = <function> defined @DBM-Core/DBM-Core.lua:7558
 StopLogging = <function> defined @DBM-Core/DBM-Core.lua:6073
 FindScenarioIDs = <function> defined @DBM-Core/DBM-Core.lua:7135
 GetNumGuildPlayersInZone = <function> defined @DBM-Core/DBM-Core.lua:2600
 VibrateController = <function> defined @DBM-Core/DBM-Core.lua:7101
 FindDungeonMapIDs = <function> defined @DBM-Core/DBM-Core.lua:7127
 GetUnitIdFromGUID = <function> defined @DBM-Core/DBM-Core.lua:2684
 CopyProfile = <function> defined @DBM-Core/DBM-Core.lua:2066
 CHAT_MSG_MONSTER_EMOTE = <function> defined @DBM-Core/DBM-Core.lua:5151
 CHAT_MSG_WHISPER = <function> defined @DBM-Core/DBM-Core.lua:6862
 SendPVPTimers = <function> defined @DBM-Core/DBM-Core.lua:6657
 DeleteProfile = <function> defined @DBM-Core/DBM-Core.lua:2083
 DungeonMusic = <table> {
 }
 ShowUpdateReminder = <function> defined @DBM-Core/modules/UpdateReminder.lua:80
 GetRaidRoster = <function> defined @DBM-Core/DBM-Core.lua:2639
 PLAYER_REGEN_DISABLED = <function> defined @DBM-Core/DBM-Core.lua:4913
 FireEvent = <function> defined @DBM-Core/DBM-Core.lua:1974
 CreateModLocalization = <function> defined @DBM-Core/modules/objects/Localization.lua:99
 SCENARIO_COMPLETED = <function> defined @DBM-Core/DBM-Core.lua:3645
 IsEnabled = <function> defined @DBM-Core/DBM-Core.lua:6943
 GetMyPlayerInfo = <function> defined @DBM-Core/DBM-Core.lua:2707
 BuildVoiceCountdownCache = <function> defined @DBM-Core/DBM-Core.lua:10554
 ADDON_LOADED = <function> defined @DBM-Core/DBM-Core.lua:1638
 lastAntiSpamFLASH = 442448.566000
 IconNumToTexture = <function> defined @DBM-Core/DBM-Core.lua:7116
 ReceiveVariableInfo = <function> defined @DBM-Core/DBM-Core.lua:6607
 registeredUnitEvents = <table> {
 }
 BattleMusic = <table> {
 }
 VoiceVersions = <table> {
 }
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @DBM-Core/DBM-Core.lua:2571
 Voices = <table> {
 }
 AddDefeatSound = <function> defined @DBM-Core/modules/Sounds.lua:123
 AddOns = <table> {
 }
 SortByMeleeRoster = <function> defined @DBM-Core/DBM-Core.lua:8050
 Options = <table> {
 }
 GetBossUnitId = <function> defined @DBM-Core/DBM-Core.lua:2844
 GetModLocalization = <function> defined @DBM-Core/modules/objects/Localization.lua:116
 AddDefaultOptions = <function> defined @DBM-Core/DBM-Core.lua:2995
 UPDATE_MOUSEOVER_UNIT = <function> defined @DBM-Core/DBM-Core.lua:4005
 ZONE_CHANGED_NEW_AREA = <function> defined @DBM-Core/DBM-Core.lua:3850
 CINEMATIC_START = <function> defined @DBM-Core/DBM-Core.lua:7202
 FilterRaidBossEmote = <function> defined @DBM-Core/DBM-Core.lua:1473
 RequestTimers = <function> defined @DBM-Core/DBM-Core.lua:6554
 GetMusic = <function> defined @DBM-Core/modules/Sounds.lua:245
 Music = <table> {
 }
 SortByGroup = <function> defined @DBM-Core/DBM-Core.lua:7999
 GetBattleMusic = <function> defined @DBM-Core/modules/Sounds.lua:211
 RAID_BOSS_WHISPER = <function> defined @DBM-Core/DBM-Core.lua:5173
 UPDATE_BATTLEFIELD_STATUS = <function> defined @DBM-Core/DBM-Core.lua:3623
 GetDungeonMusic = <function> defined @DBM-Core/modules/Sounds.lua:163
 CheckNearby = <function> defined @

**To Reproduce**
Working on the United Again storyline
Accepted The Last Conflict quest in the chain.
Entered the Azure Vault instance. (First occurrence of error)
Finished Quest and exited instance (second occurrence of error)

**Screenshots**
N/A

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
10.2.20

**Was it working in a previous version? If yes, which was the last good one?**
Yes. No error occurred when running it using 10.2.19 that I recall.

**Additional context**

**Comment by emmericp** [comment]
Thanks for reporting, fixed in https://github.com/DeadlyBossMods/DBM-Retail/issues/986
