### ISSUE TITLE
Airhorn still playing

### ISSUE THREAD

**Issue by Shredded5** [DeadlyBossMods/DBM-Retail#994]
Been trying to configure settings for couple of the bosses Fyrakk and Tindral. For Fyrakk its the announcement of the Apocalypse Roar and for Tindral it's the announcement of the flaming seeds or germination. They still play the airhorn sound even though I have it set to play a different sound. Something i'm doing wrong or somehow hidden somewhere?

**Comment by MysticalOS** [comment]
Most often, when users think airhorn is coming from DBM, it's always a weak aura.

DBM doesn't even play airhorn by default ANYWHERE unless you disabled voice packs. Did you disable voice packs?
