### ISSUE TITLE
DBM Not Playing Nice With Bazooka/Broker Everything

### ISSUE THREAD

**Issue by SisrenWarrior** [DeadlyBossMods/DBM-Retail#996]
Odd bug here, considering I have no idea why DBM would mess with these addons, but there seems to be a problem with the way DBM plays with both Bazooka and/or Broker Everything (specifically, clicking on the Professions broker throws a LUA error rather than opening up the profession list).
I'm pretty sure DBM is at fault since it's the only one of the three that has been recently updated, but I am also posting the bug in the other two just in case.

To Reproduce: Have DBM Core, Broker Everything and Bazooka installed and enabled. Enable the Profession broker within Bazooka. Left click the Profession broker - LUA error happens instead of profession list displaying. This happens even with only these three addons enabled.

Using DBM version 10.2.27 and the latest version of both Bazooka and Broker Everything. Everything worked fine with the previous version of DBM.

<details><summary>LUA Error Message</summary>
<p>

2x ...ns/DBM-Core/Libs/LibDropDownMenu-37/LibDropDownMenu.lua:794: attempt to index field 'NewFeature' (a nil value)
[string "@DBM-Core/Libs/LibDropDownMenu-37/LibDropDownMenu.lua"]:794: in function `UIDropDownMenu_AddButton'
[string "@DBM-Core/Libs/LibDropDownMenu-37/LibDropDownMenu_EasyMenu.lua"]:33: in function `initFunction'
[string "@DBM-Core/Libs/LibDropDownMenu-37/LibDropDownMenu.lua"]:138: in function `UIDropDownMenu_Initialize'
[string "@DBM-Core/Libs/LibDropDownMenu-37/LibDropDownMenu_EasyMenu.lua"]:24: in function `EasyMenu'
[string "@Broker_Everything/shared.lua"]:1965: in function `ShowMenu'
[string "@Broker_Everything/modules/professions.lua"]:664: in function `func'
[string "@Broker_Everything/shared.lua"]:2092: in function `func'
[string "@Broker_Everything/modules.lua"]:64: in function `OnClick'
[string "@Bazooka/Bazooka.lua"]:1417: in function <Bazooka/Bazooka.lua:1414>

Locals:
info = <table> {
 notClickable = false
 disabled = true
 notCheckable = true
 isNotRadio = true
 index = 1
 isTitle = true
 text = "Open"
 keepShownOnClick = true
 noClickSound = true
 hasArrow = false
}
level = 1
listFrame = LibDropDownMenu_List1 {
 0 = <userdata>
 numButtons = 1
 maxWidth = 0
}
index = 1
width = nil
listFrameName = "LibDropDownMenu_List1"
button = LibDropDownMenu_List1Button1 {
 0 = <userdata>
 hasArrow = false
 Highlight = LibDropDownMenu_List1Button1Highlight {
 }
 notCheckable = true
 Icon = LibDropDownMenu_List1Button1Icon {
 }
 invisibleButton = LibDropDownMenu_List1Button1InvisibleButton {
 }
 value = "Open"
 ColorSwatch = LibDropDownMenu_List1Button1ColorSwatch {
 }
 NormalText = LibDropDownMenu_List1Button1NormalText {
 }
 ExpandArrow = LibDropDownMenu_List1Button1ExpandArrow {
 }
 Check = LibDropDownMenu_List1Button1Check {
 }
 keepShownOnClick = true
 noClickSound = true
 UnCheck = LibDropDownMenu_List1Button1UnCheck {
 }
}
normalText = LibDropDownMenu_List1Button1NormalText {
 0 = <userdata>
}
icon = LibDropDownMenu_List1Button1Icon {
 0 = <userdata>
}
invisibleButton = LibDropDownMenu_List1Button1InvisibleButton {
 0 = <userdata>
}
expandArrow = LibDropDownMenu_List1Button1ExpandArrow {
 OnMouseDown = <function> defined @Broker_Everything/libs/LibDropDownMenu/LibDropDownMenuTemplates.lua:56
 OnEnter = <function> defined @Broker_Everything/libs/LibDropDownMenu/LibDropDownMenuTemplates.lua:43
 0 = <userdata>
}
xPos = 15
buttonHeight = 16
yPos = -15
displayInfo = LibDropDownMenu_List1Button1NormalText {
 0 = <userdata>
}
frame = Broker_Everything_LibDropDownMenu {
 0 = <userdata>
 menuList = <table> {
 }
 AddConfig = <function> defined @Broker_Everything/shared.lua:1885
 Right = Broker_Everything_LibDropDownMenuRight {
 }
 Left = Broker_Everything_LibDropDownMenuLeft {
 }
 AddEntry = <function> defined @Broker_Everything/shared.lua:1669
 Button = Broker_Everything_LibDropDownMenuButton {
 }
 Icon = Broker_Everything_LibDropDownMenuIcon {
 }
 Text = Broker_Everything_LibDropDownMenuText {
 }
 ShowMenu = <function> defined @Broker_Everything/shared.lua:1957
 Refresh = <function> defined @Broker_Everything/shared.lua:1942
 displayMode = "MENU"
 InitializeMenu = <function> defined @Broker_Everything/shared.lua:1950
 IsPrevSeparator = false
 initialize = <function> defined @DBM-Core/Libs/LibDropDownMenu/LibDropDownMenu_EasyMenu.lua:28
 AddConfigEntry = <function> defined @Broker_Everything/shared.lua:1796
 controlGroups = <table> {
 }
 menu = <table> {
 }
 Middle = Broker_Everything_LibDropDownMenuMiddle {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = "1"
(*temporary) = "UnCheck"
(*temporary) = 1
(*temporary) = 1
(*temporary) = LibDropDownMenu_List1Button1 {
 0 = <userdata>
 hasArrow = false
 Highlight = LibDropDownMenu_List1Button1Highlight {
 }
 notCheckable = true
 Icon = LibDropDownMenu_List1Button1Icon {
 }
 invisibleButton = LibDropDownMenu_List1Button1InvisibleButton {
 }
 value = "Open"
 ColorSwatch = LibDropDownMenu_List1Button1ColorSwatch {
 }
 NormalText = LibDropDownMenu_List1Button1NormalText {
 }
 ExpandArrow = LibDropDownMenu_List1Button1ExpandArrow {
 }
 Check = LibDropDownMenu_List1Button1Check {
 }
 keepShownOnClick = true
 noClickSound = true
 UnCheck = LibDropDownMenu_List1Button1UnCheck {
 }
}
(*temporary) = nil
(*temporary) = Broker_Everything_LibDropDownMenu {
 0 = <userdata>
 menuList = <table> {
 }
 AddConfig = <function> defined @Broker_Everything/shared.lua:1885
 Right = Broker_Everything_LibDropDownMenuRight {
 }
 Left = Broker_Everything_LibDropDownMenuLeft {
 }
 AddEntry = <function> defined @Broker_Everything/shared.lua:1669
 Button = Broker_Everything_LibDropDownMenuButton {
 }
 Icon = Broker_Everything_LibDropDownMenuIcon {
 }
 Text = Broker_Everything_LibDropDownMenuText {
 }
 ShowMenu = <function> defined @Broker_Everything/s

</p>
</details>

**Comment by MysticalOS** [comment]
I use DBM and bazooka for years, DBM does not do anything special here. the stack trace actually shows problem originates in broker everything and it's interaction with LibDropDownMenu

Which means it's not likely something we can address. We don't make the lib we just use it correctly. that broker everything addon is having a conflict with that lib so you'll probably want to reach out to them to make sure their addon is compatible with that lib, or leave a ticket on the lib itself if issue is there. hard to say, but it's not in DBM, we're just using a public lib.

**Comment by SisrenWarrior** [comment]
Interesting. Yes, already reached out to them also. Thanks for the quick reply!
